<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0-windows10.0.19041.0</TargetFramework>
	  <OutputPath>..\bin</OutputPath>
	  <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DCF.UX.WPF" Version="2.0.6" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DDPM.UI.Common\DDPM.UI.Common.csproj" />
    <ProjectReference Include="..\DDPM.UI.Plugin.Common\DDPM.UI.Plugin.Common.csproj" />
  </ItemGroup>

</Project>
