<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
		<SignAssembly>False</SignAssembly>
		<BaseOutputPath>..\..\bin\CommonDll</BaseOutputPath>
		<Version>2.0.0.5</Version>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="DellClientFramework" Version="6.4.5.1" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\VcpCore.Common\VcpCore.Common.csproj" />
	</ItemGroup>
	<Target Name="PostBuild" AfterTargets="PostBuildEvent">
		<Exec Command="xcopy &quot;$(ProjectDir)$(OutDir)*.*&quot; &quot;$(SolutionDir)..\DDPM.UI\CommonDll\&quot; /Y /S /Q" />
	</Target>
</Project>
