<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	  <UseWPF>true</UseWPF>
	  <BaseOutputPath>..\..\bin\CommonDll</BaseOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="imgs\cursor\FistCursor.cur" />
    <None Remove="imgs\cursor\HandCursor.cur" />
    <None Remove="Imgs\ddpm-24-dark.png" />
    <None Remove="Imgs\ddpm-24-light.png" />
    <None Remove="Imgs\ddpm-dark.png" />
    <None Remove="Imgs\ddpm-light.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="DCF.UX.WPF" Version="2.3.14.3" />
  </ItemGroup>
	<ItemGroup>
	  <ProjectReference Include="..\DDPM.SA.Common\DDPM.SA.Common.csproj" />
	  <ProjectReference Include="..\DDPM.SA.Resources\DDPM.SA.Resources.csproj" />
	</ItemGroup>
	<ItemGroup>
	  <Reference Include="DdmLibrary">
	    <HintPath>..\..\dll\DdmLibrary.dll</HintPath>
	  </Reference>
	  <Reference Include="DPeMPublic.Common">
	    <HintPath>..\..\dll\DPeMPublic.Common.dll</HintPath>
	  </Reference>
	</ItemGroup>
	<ItemGroup>
	  <Resource Include="imgs\cursor\FistCursor.cur" />
	  <Resource Include="imgs\cursor\HandCursor.cur" />
	  <Resource Include="Imgs\ddpm-24-dark.png" />
	  <Resource Include="Imgs\ddpm-24-light.png" />
	  <Resource Include="Imgs\ddpm-dark.png" />
	  <Resource Include="Imgs\ddpm-light.png" />
	</ItemGroup>
</Project>
