<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
	  <OutputPath>..\bin</OutputPath>
	  <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Background Glow.png" />
    <None Remove="EzMemoryAddApplication.xaml.bak" />
    <None Remove="EzMemoryAddApplication.xaml.cs.bak" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="DCF.UX.WPF" Version="2.3.14.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DDPM.UI.Common\DDPM.UI.Common.csproj" />
    <ProjectReference Include="..\DDPM.UI.Plugin.Common\DDPM.UI.Plugin.Common.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="DDPM.Easy.Common">
      <HintPath>..\CommonDll\DDPM.Easy.Common.dll</HintPath>
    </Reference>
    <Reference Include="DDPM.SA.Common">
      <HintPath>..\CommonDll\DDPM.SA.Common.dll</HintPath>
    </Reference>
	  <Reference Include="VcpCore.Common">
		  <HintPath>..\CommonDll\VcpCore.Common.dll</HintPath>
	  </Reference>
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Background Glow.png" />
  </ItemGroup>

</Project>
