<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
		<UseWPF>true</UseWPF>
		<Configurations>Debug;Release;Debug_NKVM</Configurations>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="DellClientFramework" Version="6.4.11.2" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\Common\DDPM.SA.Common\DDPM.SA.Common.csproj" />
		<ProjectReference Include="..\..\Common\ShowOsd\DDPM.ShowOsd.csproj" />
    <ProjectReference Include="..\..\Common\ColorApp\DDPM.ColorApp.csproj" />
    <ProjectReference Include="..\..\Common\MonitorBorker\DDPM.MonitorBorker.csproj" />
    <ProjectReference Include="..\..\Common\VcpCore.Interfaces\VcpCore.Interfaces.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <Reference Include="DdmLibrary">
	    <HintPath>..\..\dll\DdmLibrary.dll</HintPath>
	  </Reference>
	</ItemGroup>

</Project>