<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <OutputPath>..\bin</OutputPath>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
	  <Version>2.0.0.1</Version>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="WalkThroughInfo.cs" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="asset\Product_KB900.png" />
    <None Remove="asset\Product_Mouse.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.1.0" />
    <PackageReference Include="DCF.UX.WPF" Version="2.3.14.3" />
    <PackageReference Include="Dell.UCA.ThickClient.Interfaces" Version="4.3.18.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DDPM.UI.Common\DDPM.UI.Common.csproj" />
    <ProjectReference Include="..\DDPM.UI.Plugin.Common\DDPM.UI.Plugin.Common.csproj" />
    <ProjectReference Include="..\DDPM.UI.Resources\DDPM.UI.Resources.csproj" />
    <ProjectReference Include="..\DDPM.UI.WalkThroughData\DDPM.UI.WalkThroughData.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="DDPM.Easy.Common">
      <HintPath>..\CommonDll\DDPM.Easy.Common.dll</HintPath>
    </Reference>
    <Reference Include="DDPM.SA.Common">
      <HintPath>..\CommonDll\DDPM.SA.Common.dll</HintPath>
    </Reference>
    <Reference Include="DPeMPublic.Common">
      <HintPath>..\CommonDll\DPeMPublic.Common.dll</HintPath>
    </Reference>
    <Reference Include="VcpCore.Common">
      <HintPath>..\CommonDll\VcpCore.Common.dll</HintPath>
    </Reference>
    <Reference Include="VcpCore.Interfaces">
      <HintPath>..\CommonDll\VcpCore.Interfaces.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Resource Include="asset\Product_KB900.png" />
    <Resource Include="asset\Product_Mouse.png" />
  </ItemGroup>

</Project>
