<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <OutputPath>..\bin</OutputPath>
		<SignAssembly>false</SignAssembly>
		<UseWPF>true</UseWPF>
		<UseWindowsForms>true</UseWindowsForms>
		<AssemblyName>Dell.UCA.Systray</AssemblyName>
	</PropertyGroup>

	<ItemGroup>
	  <PackageReference Include="DCF.Security" Version="2.4.1" />
	  <PackageReference Include="Dell.UCA.Systray.Interfaces" Version="4.2.27.1" />
	  <PackageReference Include="Dell.UCA.SystrayCore" Version="4.2.27.1" />
	</ItemGroup>

	<ItemGroup>
	  <Compile Update="Properties\Resource.Designer.cs">
	    <DesignTime>True</DesignTime>
	    <AutoGen>True</AutoGen>
	    <DependentUpon>Resource.resx</DependentUpon>
	  </Compile>
	</ItemGroup>

	<ItemGroup>
	  <EmbeddedResource Update="Properties\Resource.resx">
	    <Generator>ResXFileCodeGenerator</Generator>
	    <LastGenOutput>Resource.Designer.cs</LastGenOutput>
	  </EmbeddedResource>
	</ItemGroup>

</Project>