<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
		<BaseOutputPath>..\..\bin\CommonDll</BaseOutputPath>
		<ImplicitUsings>disable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<Target Name="PostBuild" AfterTargets="PostBuildEvent">
	  <Exec Command="xcopy &quot;$(ProjectDir)$(OutDir)DDPM.SA.Obfuscation.*&quot; &quot;$(SolutionDir)..\DdpmSwUpdater\CommonDll\&quot; /Y /S /Q" />
	</Target>

</Project>
