<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
		<BaseOutputPath>..\..\bin\CommonDll</BaseOutputPath>
		<ImplicitUsings>disable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
	  <PackageReference Include="Obfuscar" Version="2.2.40">
	    <PrivateAssets>all</PrivateAssets>
	    <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	  </PackageReference>
	</ItemGroup>

	<ItemGroup>
	  <None Update="Obfuscar.xml">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>

	<Target Name="ObfuscarTask" AfterTargets="AfterBuild">
		<PropertyGroup>
			<ObfuscateCommand>$(Obfuscar) "Obfuscar.xml"</ObfuscateCommand>
		</PropertyGroup>
		<PropertyGroup>
			<ReplaceCommand>xcopy "$(ProjectDir)$(OutDir).Obfuscated\DDPM.SA.Obfuscation.*" "$(ProjectDir)$(OutDir)" /Y /S /Q</ReplaceCommand>
		</PropertyGroup>
		<PropertyGroup>
			<SWUpdaterCommand>xcopy "$(ProjectDir)$(OutDir).Obfuscated\DDPM.SA.Obfuscation.*" "$(SolutionDir)..\DdpmSwUpdater\CommonDll\" /Y /S /Q /C /I</SWUpdaterCommand>
		</PropertyGroup>
		<PropertyGroup>
			<RemoveTempCommand>rd /s /q "$(ProjectDir)$(OutDir).Obfuscated"</RemoveTempCommand>
		</PropertyGroup>
		<Exec WorkingDirectory="$(OutputPath)" Command="$(ObfuscateCommand)" />
		<Exec WorkingDirectory="$(OutputPath)" Command="$(ReplaceCommand)" />
		<Exec WorkingDirectory="$(OutputPath)" Command="$(SWUpdaterCommand)" />
		<Exec WorkingDirectory="$(OutputPath)" Command="$(RemoveTempCommand)" />
	</Target>

</Project>
