<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
		<OutputPath>..\bin</OutputPath>
		<SignAssembly>false</SignAssembly>
		<Nullable>disable</Nullable>
		<AssemblyName>Dell.UCA.NET.Common.Interfaces</AssemblyName>
	</PropertyGroup>

	<ItemGroup Condition="'$(TargetFramework)' == 'net472'">
		<Reference Include="System.Net.Http" Version="4.2.0" />
	</ItemGroup>

</Project>
