<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Library</OutputType>
		<TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
		<ImplicitUsings>disable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<Version>2.0.0.38</Version>
		<Configurations>Debug;Release;Debug_NKVM</Configurations>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Dell.RPC.Transport" Version="1.5.2.1" />
		<PackageReference Include="DellClientFramework" Version="6.4.5.1" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\Common\DDPM.SA.Common\DDPM.SA.Common.csproj" />
		<ProjectReference Include="..\..\Common\VcpCore.Common\VcpCore.Common.csproj" />
		<ProjectReference Include="..\..\Common\VcpCore.Interfaces\VcpCore.Interfaces.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Reference Include="DdpmJsonCommon">
			<HintPath>..\..\Common\DDPM.SA.Common\NKVM\DdpmJsonCommon.dll</HintPath>
		</Reference>
	</ItemGroup>

</Project>
