<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
		<OutputPath>..\bin</OutputPath>
		<Nullable>enable</Nullable>
		<UseWPF>true</UseWPF>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="DCF.UX.WPF" Version="2.3.14.3" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\DDPM.UI.Common\DDPM.UI.Common.csproj" />
		<ProjectReference Include="..\DDPM.UI.DdpmHomePlugin\DDPM.UI.Plugin.DdpmHomePlugin.csproj" />
		<ProjectReference Include="..\DDPM.UI.Module.WebCameraCapture\DDPM.UI.Module.WebCameraCapture.csproj" />
		<ProjectReference Include="..\DDPM.UI.Module.WebCameraSettings\DDPM.UI.Module.WebCameraSettings.csproj" />
		<ProjectReference Include="..\DDPM.UI.Module.WebColorImage\DDPM.UI.Module.WebCameraColorImage.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Reference Include="DDPM.PowerMon">
			<HintPath>..\CommonDll\DDPM.PowerMon.dll</HintPath>
		</Reference>
		<Reference Include="DDPM.SA.Common">
			<HintPath>..\CommonDll\DDPM.SA.Common.dll</HintPath>
		</Reference>
	</ItemGroup>
</Project>
