<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">

	<PropertyGroup>
		<GenerateAssemblyCompanyAttribute>false</GenerateAssemblyCompanyAttribute>
		<GenerateAssemblyFileVersionAttribute>false</GenerateAssemblyFileVersionAttribute>
		<GenerateAssemblyInformationalVersionAttribute>false</GenerateAssemblyInformationalVersionAttribute>
		<GenerateAssemblyProductAttribute>false</GenerateAssemblyProductAttribute>
		<GenerateAssemblyTitleAttribute>false</GenerateAssemblyTitleAttribute>
		<GenerateAssemblyVersionAttribute>false</GenerateAssemblyVersionAttribute>
	</PropertyGroup>

	<PropertyGroup>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<LangVersion>latest</LangVersion>
		<TreatWarningsAsErrors>false</TreatWarningsAsErrors>
		<WarningsAsErrors>;NU1605;CA1416;</WarningsAsErrors>		
	</PropertyGroup>

	<PropertyGroup>
		<!-- Repo Directories -->
		<NGATargetFrameworks>net6.0</NGATargetFrameworks>
		<NGAMultiTargetFrameworks>net472;net6.0</NGAMultiTargetFrameworks>
		<NGATargetFrameworksWindows>net6.0-windows10.0.19041.0</NGATargetFrameworksWindows>
		<UnitTestTargetFrameworks>net6.0-windows10.0.19041.0</UnitTestTargetFrameworks>
		<SrcRoot>$(MSBuildThisFileDirectory)</SrcRoot>
		<RepoRoot>$([MSBuild]::NormalizeDirectory('$(SrcRoot)', '../'))</RepoRoot>
		<!-- Base Output Directories -->
		<BaseOutputPath Condition="'$(BaseOutputPath)'==''">$([MSBuild]::NormalizeDirectory('$(RepoRoot)', 'bin'))</BaseOutputPath>
		<BaseUnitTestsOutputPath Condition="'$(BaseUnitTestsOutputPath)'==''">$([MSBuild]::NormalizeDirectory('$(RepoRoot)', 'unit_tests'))</BaseUnitTestsOutputPath>		
		<!-- Output Directories -->
		<NGAOutputPath>$(BaseOutputPath)$(Configuration)</NGAOutputPath>		
		<NGASamplePluginsOutputPath>$(BaseOutputPath)sample_plugins\$(Configuration)</NGASamplePluginsOutputPath>
		<UxLocalizationManagerSampleOutputPath>$(BaseOutputPath)UxLocalizationManagerSample\$(Configuration)</UxLocalizationManagerSampleOutputPath>
		<HelpOutputPath>$(BaseOutputPath)Help\$(Configuration)</HelpOutputPath>
		<UnitTestsOutputPath>$(BaseUnitTestsOutputPath)$(MSBuildProjectName)\$(Configuration)</UnitTestsOutputPath>
		<NGAManagerOutputPath>$(BaseOutputPath)nga_manager\$(Configuration)</NGAManagerOutputPath>		
		<NGAConsoleOutputPath>$(BaseOutputPath)nga_console\$(Configuration)</NGAConsoleOutputPath>
	</PropertyGroup>

	<Target Name="PrintVariables">
		<Message Text="NGATargetFrameworks = '$(NGATargetFrameworks)'" />
		<Message Text="NGAMultiTargetFrameworks = '$(NGAMultiTargetFrameworks)'" />
		<Message Text="NGATargetFrameworksWindows = '$(NGATargetFrameworksWindows)'" />
		<Message Text="UnitTestTargetFrameworks = '$(UnitTestTargetFrameworks)'" />
		<Message Text="SrcRoot = '$(SrcRoot)'" />
		<Message Text="RepoRoot = '$(RepoRoot)'" />
		<Message Text="BaseOutputPath = '$(BaseOutputPath)'" />
		<Message Text="NGAOutputPath = '$(NGAOutputPath)'" />
		<Message Text="HelpOutputPath = '$(HelpOutputPath)'" />
		<Message Text="UnitTestsOutputPath = '$(UnitTestsOutputPath)'" />
		<Message Text="NGASamplePluginsOutputPath = '$(NGASamplePluginsOutputPath)'" />
		<Message Text="NGAManagerOutputPath = '$(NGAManagerOutputPath)'" />		
		<Message Text="NGAConsoleOutputPath = '$(NGAConsoleOutputPath)'" />
	</Target>

	<ItemGroup>
		<Compile Include="$(MSBuildThisFileDirectory)SharedAssemblyInfo.cs">
			<Link>SharedAssemblyInfo.cs</Link>
		</Compile>
	</ItemGroup>

</Project>