//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Runtime.CompilerServices;
[assembly: System.Runtime.InteropServices.ComVisible(false)]
[assembly: System.Reflection.AssemblyDescription("Dell Display and Peripheral Manager")]
[assembly: System.Reflection.AssemblyProduct("Dell Display and Peripheral Manager")]
[assembly: System.Reflection.AssemblyTitle("Dell Display and Peripheral Manager")]
[assembly: System.Reflection.AssemblyInformationalVersion("2.0.2.10-61e493b4")]
[assembly: System.Reflection.AssemblyCompany("Dell Technologies")]
[assembly: System.Reflection.AssemblyCopyright("© 2025 Dell Technologies. All Rights Reserved")]
[assembly: System.Reflection.AssemblyFileVersion("2.0.2.10")]
[assembly: System.Reflection.AssemblyVersion("2.0.2.10")]
[assembly: InternalsVisibleTo("DDPM.UI.Module.Color.Tests, PublicKey=" +
                              "002400000480000094000000060200000024000052534131000400000100010075065fba06e04c" +
                              "14fd43e9d02540323f7bbec78c29f854af3ead4643908af773efe044dee7ae6936bdc810ea9aa9" +
                              "14f661783ce7a2c2f230fd27383c0a992c150cb82db28d4f9a939727c5be7cb12a155e95ef037a" +
                              "e9ca2467673307c477d69f79c788924229cd225e0a30d321096a50d704ab3f855de141f506c236973838d2")]
[assembly: InternalsVisibleTo("DDPM.UI.Module.Brightness.Tests, PublicKey=" +
                              "002400000480000094000000060200000024000052534131000400000100010075065fba06e04c" +
                              "14fd43e9d02540323f7bbec78c29f854af3ead4643908af773efe044dee7ae6936bdc810ea9aa9" +
                              "14f661783ce7a2c2f230fd27383c0a992c150cb82db28d4f9a939727c5be7cb12a155e95ef037a" +
                              "e9ca2467673307c477d69f79c788924229cd225e0a30d321096a50d704ab3f855de141f506c236973838d2")]
[assembly: InternalsVisibleTo("DDPM.UI.Module.DisplayOthers.Tests, PublicKey=" +
                              "002400000480000094000000060200000024000052534131000400000100010075065fba06e04c" +
                              "14fd43e9d02540323f7bbec78c29f854af3ead4643908af773efe044dee7ae6936bdc810ea9aa9" +
                              "14f661783ce7a2c2f230fd27383c0a992c150cb82db28d4f9a939727c5be7cb12a155e95ef037a" +
                              "e9ca2467673307c477d69f79c788924229cd225e0a30d321096a50d704ab3f855de141f506c236973838d2")]
[assembly: InternalsVisibleTo("DDPM.UI.Module.DisplayProperties.Tests, PublicKey=" +
                              "002400000480000094000000060200000024000052534131000400000100010075065fba06e04c" +
                              "14fd43e9d02540323f7bbec78c29f854af3ead4643908af773efe044dee7ae6936bdc810ea9aa9" +
                              "14f661783ce7a2c2f230fd27383c0a992c150cb82db28d4f9a939727c5be7cb12a155e95ef037a" +
                              "e9ca2467673307c477d69f79c788924229cd225e0a30d321096a50d704ab3f855de141f506c236973838d2")]
