<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <OutputPath>..\bin</OutputPath>
		<SignAssembly>false</SignAssembly>
		<!--<AssemblyName>Dell.UCA.Resources</AssemblyName>-->
		<Version>4.0.0</Version>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net472|AnyCPU'">
	  <TreatWarningsAsErrors>False</TreatWarningsAsErrors>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net8.0|AnyCPU'">
	  <TreatWarningsAsErrors>False</TreatWarningsAsErrors>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net472|AnyCPU'">
	  <TreatWarningsAsErrors>False</TreatWarningsAsErrors>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net8.0|AnyCPU'">
	  <TreatWarningsAsErrors>False</TreatWarningsAsErrors>
	</PropertyGroup>
<!--
	<ItemGroup>
	  <None Remove="Resources\MyDell_Blue.ico" />
	  <None Remove="Resources\SystrayIcon.ico" />
	</ItemGroup>
-->
	<ItemGroup>
		<Compile Update="Resources.Designer.cs">
			<DesignTime>True</DesignTime>
			<AutoGen>True</AutoGen>
			<DependentUpon>Resources.resx</DependentUpon>
		</Compile>
	</ItemGroup>

	<ItemGroup>
		<EmbeddedResource Update="Resources.zh-Hant.resx">
		  <Generator>PublicResXFileCodeGenerator</Generator>
		</EmbeddedResource>
		<EmbeddedResource Update="Resources.zh-Hans.resx">
		  <Generator>PublicResXFileCodeGenerator</Generator>
		</EmbeddedResource>
		<EmbeddedResource Update="Resources.ko.resx">
		  <LastGenOutput>Resources.ko.Designer.cs</LastGenOutput>
		  <Generator>PublicResXFileCodeGenerator</Generator>
		</EmbeddedResource>
		<EmbeddedResource Update="Resources.resx">
			<Generator>PublicResXFileCodeGenerator</Generator>
			<LastGenOutput>Resources.Designer.cs</LastGenOutput>
		</EmbeddedResource>
		<EmbeddedResource Update="Resources.es.resx">
		  <LastGenOutput>Resources.es.Designer.cs</LastGenOutput>
		  <Generator>PublicResXFileCodeGenerator</Generator>
		</EmbeddedResource>
		<EmbeddedResource Update="Resources.fr.resx">
		  <LastGenOutput>Resources.fr.Designer.cs</LastGenOutput>
		  <Generator>PublicResXFileCodeGenerator</Generator>
		</EmbeddedResource>
		<EmbeddedResource Update="Resources.pt-BR.resx">
		  <LastGenOutput>Resources.pt-BR.Designer.cs</LastGenOutput>
		  <Generator>PublicResXFileCodeGenerator</Generator>
		</EmbeddedResource>
		<EmbeddedResource Update="Resources.zh-CN.resx">
		  <Generator>PublicResXFileCodeGenerator</Generator>
		</EmbeddedResource>
		<EmbeddedResource Update="Resources.ja.resx">
		  <LastGenOutput>Resources.ja.Designer.cs</LastGenOutput>
		  <Generator>PublicResXFileCodeGenerator</Generator>
		</EmbeddedResource>
		<EmbeddedResource Update="Resources.es.resx">
		  <LastGenOutput>"Resources.es.Designer.cs</LastGenOutput>
		  <Generator>PublicResXFileCodeGenerator</Generator>
		</EmbeddedResource>
		<EmbeddedResource Update="Resources.de.resx">
		  <LastGenOutput>Resources.de.Designer.cs</LastGenOutput>
		  <Generator>PublicResXFileCodeGenerator</Generator>
		</EmbeddedResource>		
		<EmbeddedResource Update="Resources.zh-TW.resx">
		  <Generator>PublicResXFileCodeGenerator</Generator>
		</EmbeddedResource>
		<EmbeddedResource Update="Resources.zh.resx">
		  <Generator>PublicResXFileCodeGenerator</Generator>
		</EmbeddedResource>
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="System.Resources.Extensions" Version="8.0.0" />
		<PackageReference Include="System.Drawing.Common" Version="8.0.7" />
	</ItemGroup>

	<ItemGroup Condition="'$(TargetFramework)' == 'net472'">
		<PackageReference Include="System.Net.Http" Version="4.3.4" />
	</ItemGroup>

	<ItemGroup>
	  <Resource Include="Resources\SystrayIcon.ico" />
	</ItemGroup>
</Project>
