//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NGA.Resources {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NGA.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 About {0} 的當地語系化字串。
        /// </summary>
        public static string AboutView_Gear_Text {
            get {
                return ResourceManager.GetString("AboutView_Gear_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Dell License Agreement 的當地語系化字串。
        /// </summary>
        public static string AboutView_LicenseAgreement_Text {
            get {
                return ResourceManager.GetString("AboutView_LicenseAgreement_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 About {0} 的當地語系化字串。
        /// </summary>
        public static string AboutView_Main_Text {
            get {
                return ResourceManager.GetString("AboutView_Main_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 {0} Privacy Notice 的當地語系化字串。
        /// </summary>
        public static string AboutView_PrivacyNotice_Text {
            get {
                return ResourceManager.GetString("AboutView_PrivacyNotice_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Third Party Licenses 的當地語系化字串。
        /// </summary>
        public static string AboutView_ThirdPartyLicenses_Text {
            get {
                return ResourceManager.GetString("AboutView_ThirdPartyLicenses_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 https://www.dell.com/learn/us/en/uscorp1/terms-conditions/art-software-license-agreements 的當地語系化字串。
        /// </summary>
        public static string AboutView_Url_LicenseAgreement {
            get {
                return ResourceManager.GetString("AboutView_Url_LicenseAgreement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 https://www.dell.com/learn/us/en/uscorp1/policies-privacy 的當地語系化字串。
        /// </summary>
        public static string AboutView_Url_PrivacyNotice {
            get {
                return ResourceManager.GetString("AboutView_Url_PrivacyNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 https://dell.com/ 的當地語系化字串。
        /// </summary>
        public static string AboutView_Url_ThirdPartyLicense {
            get {
                return ResourceManager.GetString("AboutView_Url_ThirdPartyLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 V E R S I O N   3.2 的當地語系化字串。
        /// </summary>
        public static string AboutView_Version_Text {
            get {
                return ResourceManager.GetString("AboutView_Version_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Additional Notifications 的當地語系化字串。
        /// </summary>
        public static string AdditionalNotifications_Text {
            get {
                return ResourceManager.GetString("AdditionalNotifications_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 DDPM 的當地語系化字串。
        /// </summary>
        public static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Options Menu 的當地語系化字串。
        /// </summary>
        public static string CarrotMenuItem_Text {
            get {
                return ResourceManager.GetString("CarrotMenuItem_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Close 的當地語系化字串。
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }

        /// <summary>
        ///   查詢類似 To access presence sensing features, use the link below to download compatible webcam firmware 的當地語系化字串。
        /// </summary>
        public static string ColorMsg_1 {
            get {
                return ResourceManager.GetString("ColorMsg.1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Compatible Firmware 的當地語系化字串。
        /// </summary>
        public static string CompatibleFirmware {
            get {
                return ResourceManager.GetString("CompatibleFirmware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Sorry, there was an issue connecting to the host, please try again. 的當地語系化字串。
        /// </summary>
        public static string ConnectionIssue {
            get {
                return ResourceManager.GetString("ConnectionIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Yes, I consent 的當地語系化字串。
        /// </summary>
        public static string Consent_Button {
            get {
                return ResourceManager.GetString("Consent_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 © Dell Inc. or its subsidiaries. All Rights Reserved. 的當地語系化字串。
        /// </summary>
        public static string CopyRight_Text {
            get {
                return ResourceManager.GetString("CopyRight_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Critical Alerts 的當地語系化字串。
        /// </summary>
        public static string CriticalAlertsText {
            get {
                return ResourceManager.GetString("CriticalAlertsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 {0} 的當地語系化字串。
        /// </summary>
        public static string DELL_MYDELL {
            get {
                return ResourceManager.GetString("DELL_MYDELL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Learn more 的當地語系化字串。
        /// </summary>
        public static string Discovery_Notification_Button1 {
            get {
                return ResourceManager.GetString("Discovery_Notification_Button1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Remind me later 的當地語系化字串。
        /// </summary>
        public static string Discovery_Notification_Button2 {
            get {
                return ResourceManager.GetString("Discovery_Notification_Button2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Welcome to your new {0} 的當地語系化字串。
        /// </summary>
        public static string Discovery_Notification_Heading {
            get {
                return ResourceManager.GetString("Discovery_Notification_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Our tools, tips, and resources help you get the most out of your PC 的當地語系化字串。
        /// </summary>
        public static string Discovery_Notification_SubHeading {
            get {
                return ResourceManager.GetString("Discovery_Notification_SubHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Done 的當地語系化字串。
        /// </summary>
        public static string Done_Button {
            get {
                return ResourceManager.GetString("Done_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 No, I don&apos;t consent 的當地語系化字串。
        /// </summary>
        public static string DontConsent_Button {
            get {
                return ResourceManager.GetString("DontConsent_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Exit 的當地語系化字串。
        /// </summary>
        public static string EXIT {
            get {
                return ResourceManager.GetString("EXIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Explore 的當地語系化字串。
        /// </summary>
        public static string Explore {
            get {
                return ResourceManager.GetString("Explore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Inspiron 的當地語系化字串。
        /// </summary>
        public static string Inspiron {
            get {
                return ResourceManager.GetString("Inspiron", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Latitude 的當地語系化字串。
        /// </summary>
        public static string Latitude {
            get {
                return ResourceManager.GetString("Latitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Maximize 的當地語系化字串。
        /// </summary>
        public static string Maximize {
            get {
                return ResourceManager.GetString("Maximize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Minimize 的當地語系化字串。
        /// </summary>
        public static string Minimize {
            get {
                return ResourceManager.GetString("Minimize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 {0} 的當地語系化字串。
        /// </summary>
        public static string MyDell {
            get {
                return ResourceManager.GetString("MyDell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 {0} SysTray Console 的當地語系化字串。
        /// </summary>
        public static string MYDELL_APP_SYSTRAY_HEADER {
            get {
                return ResourceManager.GetString("MYDELL_APP_SYSTRAY_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 {0} SysTray Console 的當地語系化字串。
        /// </summary>
        public static string MYDELL_APP_SYSTRAY_SPLASHSCREEN {
            get {
                return ResourceManager.GetString("MYDELL_APP_SYSTRAY_SPLASHSCREEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 {0} Systray 的當地語系化字串。
        /// </summary>
        public static string MYDELL_APP_SYSTRAY_WINDOW {
            get {
                return ResourceManager.GetString("MYDELL_APP_SYSTRAY_WINDOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 {0} Console 的當地語系化字串。
        /// </summary>
        public static string MYDELL_APP_THICKCLIENT_CONSOLE_WINDOWTEXT {
            get {
                return ResourceManager.GetString("MYDELL_APP_THICKCLIENT_CONSOLE_WINDOWTEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 {0} Console 的當地語系化字串。
        /// </summary>
        public static string MYDELL_APP_THICKCLIENT_HEADER {
            get {
                return ResourceManager.GetString("MYDELL_APP_THICKCLIENT_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 {0} Console 的當地語系化字串。
        /// </summary>
        public static string MYDELL_APP_THICKCLIENT_SPLASHSCREEN {
            get {
                return ResourceManager.GetString("MYDELL_APP_THICKCLIENT_SPLASHSCREEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 {0} Console 的當地語系化字串。
        /// </summary>
        public static string MYDELL_CONSOLE {
            get {
                return ResourceManager.GetString("MYDELL_CONSOLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 MyDellConsoleHelpFileName 的當地語系化字串。
        /// </summary>
        public static string MyDellConsoleHelpFileName {
            get {
                return ResourceManager.GetString("MyDellConsoleHelpFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Previous Page 的當地語系化字串。
        /// </summary>
        public static string NarratePageBackButton {
            get {
                return ResourceManager.GetString("NarratePageBackButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Next Page 的當地語系化字串。
        /// </summary>
        public static string NarratePageForwardButton {
            get {
                return ResourceManager.GetString("NarratePageForwardButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Notifications 的當地語系化字串。
        /// </summary>
        public static string NotificationsText {
            get {
                return ResourceManager.GetString("NotificationsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 OK 的當地語系化字串。
        /// </summary>
        public static string Ok_Button {
            get {
                return ResourceManager.GetString("Ok_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Open {0}... 的當地語系化字串。
        /// </summary>
        public static string OPEN_MYDELL_THICKCLIENT {
            get {
                return ResourceManager.GetString("OPEN_MYDELL_THICKCLIENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 About... 的當地語系化字串。
        /// </summary>
        public static string OPEN_MYDELL_THICKCLIENT_ABOUT {
            get {
                return ResourceManager.GetString("OPEN_MYDELL_THICKCLIENT_ABOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Receive critical system alerts for issues that may impact performance and productivity. Restore the state of critical system notifications you may have previously dismissed. 的當地語系化字串。
        /// </summary>
        public static string Preferences_CriticalAlerts_Text {
            get {
                return ResourceManager.GetString("Preferences_CriticalAlerts_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Preferences 的當地語系化字串。
        /// </summary>
        public static string Preferences_GearMenuItem {
            get {
                return ResourceManager.GetString("Preferences_GearMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Preferences 的當地語系化字串。
        /// </summary>
        public static string Preferences_Header_Text {
            get {
                return ResourceManager.GetString("Preferences_Header_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 I want to receive notifications from {0} 的當地語系化字串。
        /// </summary>
        public static string Preferences_Notifications_Text {
            get {
                return ResourceManager.GetString("Preferences_Notifications_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 All users of this PC agree to participate in the Dell customer experience improvement program for all Dell Software. 的當地語系化字串。
        /// </summary>
        public static string Preferences_PrivacyNotice_Text {
            get {
                return ResourceManager.GetString("Preferences_PrivacyNotice_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Help us improve 的當地語系化字串。
        /// </summary>
        public static string Preferences_Title {
            get {
                return ResourceManager.GetString("Preferences_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 &lt;html lang=&quot;en&quot;&gt;
        ///
        ///&lt;head&gt;
        ///&lt;meta http-equiv=Content-Type content=&quot;text/html; charset=utf-8&quot;&gt;
        ///&lt;meta name=Generator content=&quot;Microsoft Word 15 (filtered)&quot;&gt;
        ///&lt;link href=&quot;https://fonts.googleapis.com/css2?family=Roboto&amp;display=swap&quot; rel=&quot;stylesheet&quot;&gt;
        ///&lt;style&gt;
        ///&lt;!--
        /// /* Font Definitions */
        /// @font-face
        ///	{
        ///	panose-1:5 0 0 0 0 0 0 0 0 0;}
        ///@font-face
        ///	{
        ///	panose-1:2 1 6 0 3 1 1 1 1 1;}
        ///@font-face
        ///	{
        ///	panose-1:2 4 5 3 5 4 6 3 2 4;}
        ///@font-face
        ///	{
        ///	panose-1:2 15 5 2 2 2 4 3 2 4;}
        ///@font-face
        ///	{
        ///	panose- [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        public static string PrivacyHTML {
            get {
                return ResourceManager.GetString("PrivacyHTML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Privacy Notice 的當地語系化字串。
        /// </summary>
        public static string PrivacyNoticeText {
            get {
                return ResourceManager.GetString("PrivacyNoticeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Register Product 的當地語系化字串。
        /// </summary>
        public static string ProductRegistration_GearMenuItem {
            get {
                return ResourceManager.GetString("ProductRegistration_GearMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Restore 的當地語系化字串。
        /// </summary>
        public static string Restore {
            get {
                return ResourceManager.GetString("Restore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Restore alerts 的當地語系化字串。
        /// </summary>
        public static string RestoreAlerts {
            get {
                return ResourceManager.GetString("RestoreAlerts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Return to homepage 的當地語系化字串。
        /// </summary>
        public static string ReturnToHomePage_Text {
            get {
                return ResourceManager.GetString("ReturnToHomePage_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 No features are available in {0} at this time. {0} will shutdown now. 的當地語系化字串。
        /// </summary>
        public static string Shutdown_MessageBoxText {
            get {
                return ResourceManager.GetString("Shutdown_MessageBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 (圖示) 的類型 System.Drawing.Icon 當地語系化資源。
        /// </summary>
        public static System.Drawing.Icon SystrayIcon {
            get {
                object obj = ResourceManager.GetObject("SystrayIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 By clicking Yes, you have read our 的當地語系化字串。
        /// </summary>
        public static string TelemetryConsent_Part1_Text {
            get {
                return ResourceManager.GetString("TelemetryConsent_Part1_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 , understood your rights and how Dell uses and protects your data. 的當地語系化字串。
        /// </summary>
        public static string TelemetryConsent_Part2_Text {
            get {
                return ResourceManager.GetString("TelemetryConsent_Part2_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 https://www.dell.com/learn/us/en/uscorp1/policies-privacy-country-specific-privacy-policy 的當地語系化字串。
        /// </summary>
        public static string TelemetryConsent_URL {
            get {
                return ResourceManager.GetString("TelemetryConsent_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Privacy Statement 的當地語系化字串。
        /// </summary>
        public static string TelemetryConsent_URL_Text {
            get {
                return ResourceManager.GetString("TelemetryConsent_URL_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 https://dell.com/ 的當地語系化字串。
        /// </summary>
        public static string Url_Dell {
            get {
                return ResourceManager.GetString("Url_Dell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 https://www.dell.com/support/retail-registration/ 的當地語系化字串。
        /// </summary>
        public static string Url_DellProductRegistration {
            get {
                return ResourceManager.GetString("Url_DellProductRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 User Guide 的當地語系化字串。
        /// </summary>
        public static string UserGuide_GearMenuItem {
            get {
                return ResourceManager.GetString("UserGuide_GearMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 https://www.dell.com/support/home/en-in/product-support/product/mydell/docs 的當地語系化字串。
        /// </summary>
        public static string UserGuideUrl {
            get {
                return ResourceManager.GetString("UserGuideUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Close 的當地語系化字串。
        /// </summary>
        public static string UXAlertCloseButtonAutomationText {
            get {
                return ResourceManager.GetString("UXAlertCloseButtonAutomationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Use CTRL + SHIFT in combination with the Up and Down arrows to move an item 的當地語系化字串。
        /// </summary>
        public static string UXDraggableListBoxHelpText {
            get {
                return ResourceManager.GetString("UXDraggableListBoxHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Draggable List Box 的當地語系化字串。
        /// </summary>
        public static string UXDraggableListBoxType {
            get {
                return ResourceManager.GetString("UXDraggableListBoxType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Grab Item 的當地語系化字串。
        /// </summary>
        public static string UXGrabItemType {
            get {
                return ResourceManager.GetString("UXGrabItemType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Combo box 的當地語系化字串。
        /// </summary>
        public static string UXIconComboBoxType {
            get {
                return ResourceManager.GetString("UXIconComboBoxType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Back 的當地語系化字串。
        /// </summary>
        public static string UXInfoPresenterBackButtonText {
            get {
                return ResourceManager.GetString("UXInfoPresenterBackButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Got It! 的當地語系化字串。
        /// </summary>
        public static string UXInfoPresenterDoneButtonText {
            get {
                return ResourceManager.GetString("UXInfoPresenterDoneButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Next 的當地語系化字串。
        /// </summary>
        public static string UXInfoPresenterNextButtonText {
            get {
                return ResourceManager.GetString("UXInfoPresenterNextButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Link 的當地語系化字串。
        /// </summary>
        public static string UXLinkType {
            get {
                return ResourceManager.GetString("UXLinkType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Tile 的當地語系化字串。
        /// </summary>
        public static string UXTileType {
            get {
                return ResourceManager.GetString("UXTileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 View Data Collection and Use Notice 的當地語系化字串。
        /// </summary>
        public static string ViewPrivacyNotice_Text {
            get {
                return ResourceManager.GetString("ViewPrivacyNotice_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Vostro 的當地語系化字串。
        /// </summary>
        public static string Vostro {
            get {
                return ResourceManager.GetString("Vostro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 To access Microsoft Presence Sensing features, visit Windows Settings 的當地語系化字串。
        /// </summary>
        public static string WebcamMPS_0 {
            get {
                return ResourceManager.GetString("WebcamMPS.0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Get started 的當地語系化字串。
        /// </summary>
        public static string Welcome_DetailText {
            get {
                return ResourceManager.GetString("Welcome_DetailText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Customize settings, setup software and more. 的當地語系化字串。
        /// </summary>
        public static string Welcome_SubDetailText {
            get {
                return ResourceManager.GetString("Welcome_SubDetailText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 WELCOME, {0} 的當地語系化字串。
        /// </summary>
        public static string Welcome_TitleText {
            get {
                return ResourceManager.GetString("Welcome_TitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Get started 的當地語系化字串。
        /// </summary>
        public static string WelcomeBack_DetailText {
            get {
                return ResourceManager.GetString("WelcomeBack_DetailText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Customize settings, setup software and more. 的當地語系化字串。
        /// </summary>
        public static string WelcomeBack_SubDetailText {
            get {
                return ResourceManager.GetString("WelcomeBack_SubDetailText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 WELCOME BACK, {0} 的當地語系化字串。
        /// </summary>
        public static string WelcomeBack_TitleText {
            get {
                return ResourceManager.GetString("WelcomeBack_TitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Window Handle Error 的當地語系化字串。
        /// </summary>
        public static string WindowHandleError {
            get {
                return ResourceManager.GetString("WindowHandleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 XPS 的當地語系化字串。
        /// </summary>
        public static string XPS {
            get {
                return ResourceManager.GetString("XPS", resourceCulture);
            }
        }
    }
}
