//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NGA.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NGA.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About {0}.
        /// </summary>
        public static string AboutView_Gear_Text {
            get {
                return ResourceManager.GetString("AboutView_Gear_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dell License Agreement.
        /// </summary>
        public static string AboutView_LicenseAgreement_Text {
            get {
                return ResourceManager.GetString("AboutView_LicenseAgreement_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About {0}.
        /// </summary>
        public static string AboutView_Main_Text {
            get {
                return ResourceManager.GetString("AboutView_Main_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Privacy Notice.
        /// </summary>
        public static string AboutView_PrivacyNotice_Text {
            get {
                return ResourceManager.GetString("AboutView_PrivacyNotice_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Third Party Licenses.
        /// </summary>
        public static string AboutView_ThirdPartyLicenses_Text {
            get {
                return ResourceManager.GetString("AboutView_ThirdPartyLicenses_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.dell.com/learn/us/en/uscorp1/terms-conditions/art-software-license-agreements.
        /// </summary>
        public static string AboutView_Url_LicenseAgreement {
            get {
                return ResourceManager.GetString("AboutView_Url_LicenseAgreement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.dell.com/learn/us/en/uscorp1/policies-privacy.
        /// </summary>
        public static string AboutView_Url_PrivacyNotice {
            get {
                return ResourceManager.GetString("AboutView_Url_PrivacyNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://dell.com/.
        /// </summary>
        public static string AboutView_Url_ThirdPartyLicense {
            get {
                return ResourceManager.GetString("AboutView_Url_ThirdPartyLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V E R S I O N   3.2.
        /// </summary>
        public static string AboutView_Version_Text {
            get {
                return ResourceManager.GetString("AboutView_Version_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Notifications.
        /// </summary>
        public static string AdditionalNotifications_Text {
            get {
                return ResourceManager.GetString("AdditionalNotifications_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DDPM.
        /// </summary>
        public static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options Menu.
        /// </summary>
        public static string CarrotMenuItem_Text {
            get {
                return ResourceManager.GetString("CarrotMenuItem_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, there was an issue connecting to the host, please try again..
        /// </summary>
        public static string ConnectionIssue {
            get {
                return ResourceManager.GetString("ConnectionIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, I consent.
        /// </summary>
        public static string Consent_Button {
            get {
                return ResourceManager.GetString("Consent_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to © Dell Inc. or its subsidiaries. All Rights Reserved..
        /// </summary>
        public static string CopyRight_Text {
            get {
                return ResourceManager.GetString("CopyRight_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Critical Alerts.
        /// </summary>
        public static string CriticalAlertsText {
            get {
                return ResourceManager.GetString("CriticalAlertsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        public static string DELL_MYDELL {
            get {
                return ResourceManager.GetString("DELL_MYDELL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn more.
        /// </summary>
        public static string Discovery_Notification_Button1 {
            get {
                return ResourceManager.GetString("Discovery_Notification_Button1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remind me later.
        /// </summary>
        public static string Discovery_Notification_Button2 {
            get {
                return ResourceManager.GetString("Discovery_Notification_Button2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to your new {0}.
        /// </summary>
        public static string Discovery_Notification_Heading {
            get {
                return ResourceManager.GetString("Discovery_Notification_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our tools, tips, and resources help you get the most out of your PC.
        /// </summary>
        public static string Discovery_Notification_SubHeading {
            get {
                return ResourceManager.GetString("Discovery_Notification_SubHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        public static string Done_Button {
            get {
                return ResourceManager.GetString("Done_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No, I don&apos;t consent.
        /// </summary>
        public static string DontConsent_Button {
            get {
                return ResourceManager.GetString("DontConsent_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string EXIT {
            get {
                return ResourceManager.GetString("EXIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explore.
        /// </summary>
        public static string Explore {
            get {
                return ResourceManager.GetString("Explore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inspiron.
        /// </summary>
        public static string Inspiron {
            get {
                return ResourceManager.GetString("Inspiron", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude.
        /// </summary>
        public static string Latitude {
            get {
                return ResourceManager.GetString("Latitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximize.
        /// </summary>
        public static string Maximize {
            get {
                return ResourceManager.GetString("Maximize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize.
        /// </summary>
        public static string Minimize {
            get {
                return ResourceManager.GetString("Minimize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        public static string MyDell {
            get {
                return ResourceManager.GetString("MyDell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} SysTray Console.
        /// </summary>
        public static string MYDELL_APP_SYSTRAY_HEADER {
            get {
                return ResourceManager.GetString("MYDELL_APP_SYSTRAY_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} SysTray Console.
        /// </summary>
        public static string MYDELL_APP_SYSTRAY_SPLASHSCREEN {
            get {
                return ResourceManager.GetString("MYDELL_APP_SYSTRAY_SPLASHSCREEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Systray.
        /// </summary>
        public static string MYDELL_APP_SYSTRAY_WINDOW {
            get {
                return ResourceManager.GetString("MYDELL_APP_SYSTRAY_WINDOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Console.
        /// </summary>
        public static string MYDELL_APP_THICKCLIENT_CONSOLE_WINDOWTEXT {
            get {
                return ResourceManager.GetString("MYDELL_APP_THICKCLIENT_CONSOLE_WINDOWTEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Console.
        /// </summary>
        public static string MYDELL_APP_THICKCLIENT_HEADER {
            get {
                return ResourceManager.GetString("MYDELL_APP_THICKCLIENT_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Console.
        /// </summary>
        public static string MYDELL_APP_THICKCLIENT_SPLASHSCREEN {
            get {
                return ResourceManager.GetString("MYDELL_APP_THICKCLIENT_SPLASHSCREEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Console.
        /// </summary>
        public static string MYDELL_CONSOLE {
            get {
                return ResourceManager.GetString("MYDELL_CONSOLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MyDellConsoleHelpFileName.
        /// </summary>
        public static string MyDellConsoleHelpFileName {
            get {
                return ResourceManager.GetString("MyDellConsoleHelpFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Page.
        /// </summary>
        public static string NarratePageBackButton {
            get {
                return ResourceManager.GetString("NarratePageBackButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next Page.
        /// </summary>
        public static string NarratePageForwardButton {
            get {
                return ResourceManager.GetString("NarratePageForwardButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        public static string NotificationsText {
            get {
                return ResourceManager.GetString("NotificationsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Ok_Button {
            get {
                return ResourceManager.GetString("Ok_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open {0}....
        /// </summary>
        public static string OPEN_MYDELL_THICKCLIENT {
            get {
                return ResourceManager.GetString("OPEN_MYDELL_THICKCLIENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About....
        /// </summary>
        public static string OPEN_MYDELL_THICKCLIENT_ABOUT {
            get {
                return ResourceManager.GetString("OPEN_MYDELL_THICKCLIENT_ABOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive critical system alerts for issues that may impact performance and productivity. Restore the state of critical system notifications you may have previously dismissed..
        /// </summary>
        public static string Preferences_CriticalAlerts_Text {
            get {
                return ResourceManager.GetString("Preferences_CriticalAlerts_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferences.
        /// </summary>
        public static string Preferences_GearMenuItem {
            get {
                return ResourceManager.GetString("Preferences_GearMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferences.
        /// </summary>
        public static string Preferences_Header_Text {
            get {
                return ResourceManager.GetString("Preferences_Header_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I want to receive notifications from {0}.
        /// </summary>
        public static string Preferences_Notifications_Text {
            get {
                return ResourceManager.GetString("Preferences_Notifications_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All users of this PC agree to participate in the Dell customer experience improvement program for all Dell Software..
        /// </summary>
        public static string Preferences_PrivacyNotice_Text {
            get {
                return ResourceManager.GetString("Preferences_PrivacyNotice_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help us improve.
        /// </summary>
        public static string Preferences_Title {
            get {
                return ResourceManager.GetString("Preferences_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html lang=&quot;en&quot;&gt;
        ///
        ///&lt;head&gt;
        ///&lt;meta http-equiv=Content-Type content=&quot;text/html; charset=utf-8&quot;&gt;
        ///&lt;meta name=Generator content=&quot;Microsoft Word 15 (filtered)&quot;&gt;
        ///&lt;link href=&quot;https://fonts.googleapis.com/css2?family=Roboto&amp;display=swap&quot; rel=&quot;stylesheet&quot;&gt;
        ///&lt;style&gt;
        ///&lt;!--
        /// /* Font Definitions */
        /// @font-face
        ///	{
        ///	panose-1:5 0 0 0 0 0 0 0 0 0;}
        ///@font-face
        ///	{
        ///	panose-1:2 1 6 0 3 1 1 1 1 1;}
        ///@font-face
        ///	{
        ///	panose-1:2 4 5 3 5 4 6 3 2 4;}
        ///@font-face
        ///	{
        ///	panose-1:2 15 5 2 2 2 4 3 2 4;}
        ///@font-face
        ///	{
        ///	panose- [rest of string was truncated]&quot;;.
        /// </summary>
        public static string PrivacyHTML {
            get {
                return ResourceManager.GetString("PrivacyHTML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Notice.
        /// </summary>
        public static string PrivacyNoticeText {
            get {
                return ResourceManager.GetString("PrivacyNoticeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register Product.
        /// </summary>
        public static string ProductRegistration_GearMenuItem {
            get {
                return ResourceManager.GetString("ProductRegistration_GearMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore.
        /// </summary>
        public static string Restore {
            get {
                return ResourceManager.GetString("Restore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore alerts.
        /// </summary>
        public static string RestoreAlerts {
            get {
                return ResourceManager.GetString("RestoreAlerts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return to homepage.
        /// </summary>
        public static string ReturnToHomePage_Text {
            get {
                return ResourceManager.GetString("ReturnToHomePage_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No features are available in {0} at this time. {0} will shutdown now..
        /// </summary>
        public static string Shutdown_MessageBoxText {
            get {
                return ResourceManager.GetString("Shutdown_MessageBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon SystrayIcon {
            get {
                object obj = ResourceManager.GetObject("SystrayIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By clicking Yes, you have read our.
        /// </summary>
        public static string TelemetryConsent_Part1_Text {
            get {
                return ResourceManager.GetString("TelemetryConsent_Part1_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , understood your rights and how Dell uses and protects your data..
        /// </summary>
        public static string TelemetryConsent_Part2_Text {
            get {
                return ResourceManager.GetString("TelemetryConsent_Part2_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.dell.com/learn/us/en/uscorp1/policies-privacy-country-specific-privacy-policy.
        /// </summary>
        public static string TelemetryConsent_URL {
            get {
                return ResourceManager.GetString("TelemetryConsent_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Statement.
        /// </summary>
        public static string TelemetryConsent_URL_Text {
            get {
                return ResourceManager.GetString("TelemetryConsent_URL_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://dell.com/.
        /// </summary>
        public static string Url_Dell {
            get {
                return ResourceManager.GetString("Url_Dell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.dell.com/support/retail-registration/.
        /// </summary>
        public static string Url_DellProductRegistration {
            get {
                return ResourceManager.GetString("Url_DellProductRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Guide.
        /// </summary>
        public static string UserGuide_GearMenuItem {
            get {
                return ResourceManager.GetString("UserGuide_GearMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.dell.com/support/home/en-in/product-support/product/mydell/docs.
        /// </summary>
        public static string UserGuideUrl {
            get {
                return ResourceManager.GetString("UserGuideUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string UXAlertCloseButtonAutomationText {
            get {
                return ResourceManager.GetString("UXAlertCloseButtonAutomationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use CTRL + SHIFT in combination with the Up and Down arrows to move an item.
        /// </summary>
        public static string UXDraggableListBoxHelpText {
            get {
                return ResourceManager.GetString("UXDraggableListBoxHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draggable List Box.
        /// </summary>
        public static string UXDraggableListBoxType {
            get {
                return ResourceManager.GetString("UXDraggableListBoxType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grab Item.
        /// </summary>
        public static string UXGrabItemType {
            get {
                return ResourceManager.GetString("UXGrabItemType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Combo box.
        /// </summary>
        public static string UXIconComboBoxType {
            get {
                return ResourceManager.GetString("UXIconComboBoxType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string UXInfoPresenterBackButtonText {
            get {
                return ResourceManager.GetString("UXInfoPresenterBackButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Got It!.
        /// </summary>
        public static string UXInfoPresenterDoneButtonText {
            get {
                return ResourceManager.GetString("UXInfoPresenterDoneButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string UXInfoPresenterNextButtonText {
            get {
                return ResourceManager.GetString("UXInfoPresenterNextButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link.
        /// </summary>
        public static string UXLinkType {
            get {
                return ResourceManager.GetString("UXLinkType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tile.
        /// </summary>
        public static string UXTileType {
            get {
                return ResourceManager.GetString("UXTileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Data Collection and Use Notice.
        /// </summary>
        public static string ViewPrivacyNotice_Text {
            get {
                return ResourceManager.GetString("ViewPrivacyNotice_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vostro.
        /// </summary>
        public static string Vostro {
            get {
                return ResourceManager.GetString("Vostro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get started.
        /// </summary>
        public static string Welcome_DetailText {
            get {
                return ResourceManager.GetString("Welcome_DetailText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customize settings, setup software and more..
        /// </summary>
        public static string Welcome_SubDetailText {
            get {
                return ResourceManager.GetString("Welcome_SubDetailText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WELCOME, {0}.
        /// </summary>
        public static string Welcome_TitleText {
            get {
                return ResourceManager.GetString("Welcome_TitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get started.
        /// </summary>
        public static string WelcomeBack_DetailText {
            get {
                return ResourceManager.GetString("WelcomeBack_DetailText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customize settings, setup software and more..
        /// </summary>
        public static string WelcomeBack_SubDetailText {
            get {
                return ResourceManager.GetString("WelcomeBack_SubDetailText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WELCOME BACK, {0}.
        /// </summary>
        public static string WelcomeBack_TitleText {
            get {
                return ResourceManager.GetString("WelcomeBack_TitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window Handle Error.
        /// </summary>
        public static string WindowHandleError {
            get {
                return ResourceManager.GetString("WindowHandleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XPS.
        /// </summary>
        public static string XPS {
            get {
                return ResourceManager.GetString("XPS", resourceCulture);
            }
        }
    }
}
