<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
		<SignAssembly>False</SignAssembly>
		<AssemblyOriginatorKeyFile></AssemblyOriginatorKeyFile>
		<BaseOutputPath>..\..\bin\CommonDll</BaseOutputPath>
		<Version>2.0.0.5</Version>
		<Configurations>Debug;Release;Debug_NKVM</Configurations>
	</PropertyGroup>
	
	<ItemGroup>
    <PackageReference Include="DellClientFramework" Version="6.4.5.1" />
	</ItemGroup>
	
	<Target Name="PostBuild" AfterTargets="PostBuildEvent">
	  <Exec Command="xcopy &quot;$(ProjectDir)$(OutDir)VcpCore.Common.*&quot; &quot;$(SolutionDir)..\DdpmSwUpdater\CommonDll\&quot; /Y /S /Q" />
	</Target>

</Project>
