<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
		<OutputPath>..\bin</OutputPath>
		<SignAssembly>false</SignAssembly>
		<Nullable>disable</Nullable>
		<AssemblyName>Dell.UCA.NET.Common</AssemblyName>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\NGA.NET.Common.Interfaces\NGA.NET.Common.Interfaces.csproj" />
		<PackageReference Include="DellClientFramework" Version="6.4.11.2" />
	</ItemGroup>
  
	<ItemGroup Condition="'$(TargetFramework)' == 'net472'">
		<PackageReference Include="System.Net.Http" Version="4.3.4" />
		<PackageReference Include="System.Text.Encodings.Web" Version="6.0.0" />
    <PackageReference Include="System.Text.Json" Version="6.0.6" />
  </ItemGroup>
</Project>
