<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
		<BaseOutputPath>..\..\bin\CommonDll</BaseOutputPath>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
		<UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DellClientFramework" Version="6.4.11.2" />
  </ItemGroup>

</Project>
