<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
		<OutputPath>..\bin</OutputPath>
		<Nullable>enable</Nullable>
		<UseWPF>true</UseWPF>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>

	<ItemGroup>
	  <None Remove="Resources\Background_Glow.png" />
	  <None Remove="Resources\double arrow blue.png" />
	  <None Remove="Resources\double arrow.png" />
	  <None Remove="Resources\Lock.png" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="CommunityToolkit.Mvvm" Version="8.1.0" />
		<PackageReference Include="DCF.UX.WPF" Version="2.3.14.3" />
		<PackageReference Include="Dell.UCA.ThickClient.Interfaces" Version="4.3.18.3" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\DDPM.UI.Common\DDPM.UI.Common.csproj" />
		<ProjectReference Include="..\DDPM.UI.DdpmHomePlugin\DDPM.UI.Plugin.DdpmHomePlugin.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Reference Include="DDPM.SA.Common">
			<HintPath>..\CommonDll\DDPM.SA.Common.dll</HintPath>
		</Reference>
		<Reference Include="DPeMPublic.Common">
		  <HintPath>..\CommonDll\DPeMPublic.Common.dll</HintPath>
		</Reference>
		<Reference Include="VcpCore.Common">
		  <HintPath>..\CommonDll\VcpCore.Common.dll</HintPath>
		</Reference>
	</ItemGroup>

	<ItemGroup>
	  <Resource Include="Resources\Background_Glow.png">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </Resource>
	  <Resource Include="Resources\double arrow blue.png">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </Resource>
	  <Resource Include="Resources\double arrow.png">
	    <CopyToOutputDirectory>Always</CopyToOutputDirectory>
	  </Resource>
	  <Resource Include="Resources\Lock.png" />
	</ItemGroup>

	<ItemGroup>
	  <Compile Update="General\Settings_General.xaml.cs">
	    <SubType>Code</SubType>
	  </Compile>
	  <Compile Update="About\Settings_About.xaml.cs">
	    <SubType>Code</SubType>
	  </Compile>
	  <Compile Update="WidgeSettings\Settings_WidgetSettings.xaml.cs">
	    <SubType>Code</SubType>
	  </Compile>
	  <Compile Update="About\ThirdPartyLicenses.xaml.cs">
	    <SubType>Code</SubType>
	  </Compile>
	</ItemGroup>

	<ItemGroup>
	  <Page Update="WidgeSettings\Settings_WidgetSettings.xaml">
	    <SubType>Designer</SubType>
	  </Page>
	</ItemGroup>


</Project>
