<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <OutputPath>..\bin</OutputPath>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <TreatWarningsAsErrors>False</TreatWarningsAsErrors>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <TreatWarningsAsErrors>False</TreatWarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Models\**" />
    <Compile Remove="Themes\**" />
    <Compile Remove="UserControls\**" />
    <EmbeddedResource Remove="Models\**" />
    <EmbeddedResource Remove="Themes\**" />
    <EmbeddedResource Remove="UserControls\**" />
    <None Remove="Models\**" />
    <None Remove="Themes\**" />
    <None Remove="UserControls\**" />
    <Page Remove="Models\**" />
    <Page Remove="Themes\**" />
    <Page Remove="UserControls\**" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="D:\DDPM\DDPM.UI\SharedAssemblyInfo.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="DCF.UX.WPF" Version="2.2.4.1" />
    <PackageReference Include="Dell.UCA.ThickClient.Interfaces" Version="4.2.27.1" />
    <!--<PackageReference Include="Microsoft.CodeAnalysis.NetAnalyzers" Version="5.0.3">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>-->
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DDPM.UI.Common\DDPM.UI.Common.csproj" />
    <ProjectReference Include="..\DDPM.UI.Module.WebCameraCapture\DDPM.UI.Module.WebCameraCapture.csproj" />
    <ProjectReference Include="..\DDPM.UI.Module.WebCameraMicrophone\DDPM.UI.Module.WebCameraMicrophone.csproj" />
    <ProjectReference Include="..\DDPM.UI.Module.WebCameraPresenceDetection\DDPM.UI.Module.WebCameraPresenceDetection.csproj" />    
    <ProjectReference Include="..\DDPM.UI.Module.WebCameraSettings\DDPM.UI.Module.WebCameraSettings.csproj" />    
    <ProjectReference Include="..\DDPM.UI.Module.WebColorImage\DDPM.UI.Module.WebCameraColorImage.csproj" />
    <ProjectReference Include="..\DDPM.UI.Plugin.Common\DDPM.UI.Plugin.Common.csproj" />
    <ProjectReference Include="..\DDPM.UI.Resources\DDPM.UI.Resources.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="DDPM.SA.Common">
      <HintPath>..\CommonDll\DDPM.SA.Common.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
