<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
		<BaseOutputPath></BaseOutputPath>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="DDPM.Peripherals.interface" Version="2.0.0.3-beta" />
		<PackageReference Include="Dell.TechHub.Sdk.Common.Identifiers" Version="3.0.0.606-2e2db9-beta" />
		<PackageReference Include="DellClientFramework" Version="6.4.5.1" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\Common\DDPM.SA.Common\DDPM.SA.Common.csproj" />
		<ProjectReference Include="..\DDPM.SA.Plugins.User.Peripherals\DDPM.SA.Plugins.User.Peripherals.csproj" />
	</ItemGroup>

</Project>
