<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup Condition="'$(Configuration)'=='Debug'">
		<OutputType>Exe</OutputType>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)'=='Release'">
		<OutputType>WinExe</OutputType>
	</PropertyGroup>
	<PropertyGroup>
		<TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
		<ImplicitUsings>disable</ImplicitUsings>
		<BaseOutputPath>..\bin\$(MSBuildProjectName)\</BaseOutputPath>
		<Version>2.0.2.11</Version>
		<Configurations>Debug;Release;Debug_NKVM</Configurations>
		<ApplicationIcon>MyDell_Blue.ico</ApplicationIcon>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
		<Optimize>False</Optimize>
	</PropertyGroup>

	<PropertyGroup>
		<AssemblyTitle>Dell Display and Peripheral Manager</AssemblyTitle>
	</PropertyGroup>

	<ItemGroup>
		<Content Include="MyDell_Blue.ico" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Dell.UnifiedAgent.Client" Version="1.4.21.3" />
		<PackageReference Include="MessagePack" Version="3.1.3" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Common\DDPM.SA.Common\DDPM.SA.Common.csproj" />
		<ProjectReference Include="..\Common\DDPM.SA.Obfuscation\DDPM.SA.Obfuscation.csproj" />
		<ProjectReference Include="..\Plugins\CLI.Plugins.Display\CLI.Plugins.Display.csproj" />
		<ProjectReference Include="..\Plugins\CLI.Plugins.Peripherals\CLI.Plugins.Peripherals.csproj" />
		<ProjectReference Include="..\Plugins\DDPM.SA.Plugins.User.CLIProxy\DDPM.SA.Plugins.User.CLIProxy.csproj" />
		<ProjectReference Include="..\Plugins\DDPM.SA.Plugins.User.CMAProxy\DDPM.SA.Plugins.User.CMAProxy.csproj" />
		<ProjectReference Include="..\Plugins\DDPM.SA.Plugins.User.ColorPreset\DDPM.SA.Plugins.User.ColorPreset.csproj" />
		<ProjectReference Include="..\Plugins\DDPM.SA.Plugins.User.DeviceManager\DDPM.SA.Plugins.User.DeviceManager.csproj" />
		<ProjectReference Include="..\Plugins\DDPM.SA.Plugins.User.DisplayManager\DDPM.SA.Plugins.User.DisplayManager.csproj" />
		<ProjectReference Include="..\Plugins\DDPM.SA.Plugins.User.DisplayProperties\DDPM.SA.Plugins.User.DisplayProperties.csproj" />
		<ProjectReference Include="..\Plugins\DDPM.SA.Plugins.User.DTPProxy\DDPM.SA.Plugins.User.DTPProxy.csproj" />
		<ProjectReference Include="..\Plugins\DDPM.SA.Plugins.User.EasyArrange\DDPM.SA.Plugins.User.EasyArrange.csproj" />
		<ProjectReference Include="..\Plugins\DDPM.SA.Plugins.User.EazyMemory\DDPM.SA.Plugins.User.EzMemory.csproj" />
		<ProjectReference Include="..\Plugins\DDPM.SA.Plugins.User.Hotkey\DDPM.SA.Plugins.User.Hotkey.csproj" />
		<ProjectReference Include="..\Plugins\DDPM.SA.Plugins.User.NetworkKVM\DDPM.SA.Plugins.User.NetworkKVM.csproj" />
		<ProjectReference Include="..\Plugins\DDPM.SA.Plugins.User.Peripherals\DDPM.SA.Plugins.User.Peripherals.csproj" />
		<ProjectReference Include="..\Plugins\DDPM.SA.Plugins.User.PipPbpManager\DDPM.SA.Plugins.User.PipPbpManager.csproj" />
		<ProjectReference Include="..\Plugins\DDPM.SA.Plugins.User.SchedulerManager\DDPM.SA.Plugins.User.SchedulerManager.csproj" />
		<ProjectReference Include="..\Plugins\DDPM.SA.Plugins.User.SettingsManager\DDPM.SA.Plugins.User.SettingsManager.csproj" />
		<ProjectReference Include="..\Plugins\DDPM.SA.Plugins.User.TelementryScheduler\DDPM.SA.Plugins.User.TelementryScheduler.csproj" />
		<ProjectReference Include="..\Plugins\DDPM.SA.Plugins.User.USBKVM\DDPM.SA.Plugins.User.USBKVM.csproj" />
		<ProjectReference Include="..\Plugins\VcpCore.Plugins\VcpCore.Plugins.csproj" />
	</ItemGroup>

</Project>
