<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <OutputPath>..\bin</OutputPath>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <TreatWarningsAsErrors>False</TreatWarningsAsErrors>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <TreatWarningsAsErrors>False</TreatWarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Interfaces\**" />
    <Compile Remove="Models\**" />
    <Compile Remove="Themes\**" />
    <Compile Remove="UserControls\**" />
    <Compile Remove="ViewModels\**" />
    <EmbeddedResource Remove="Interfaces\**" />
    <EmbeddedResource Remove="Models\**" />
    <EmbeddedResource Remove="Themes\**" />
    <EmbeddedResource Remove="UserControls\**" />
    <EmbeddedResource Remove="ViewModels\**" />
    <None Remove="Interfaces\**" />
    <None Remove="Models\**" />
    <None Remove="Themes\**" />
    <None Remove="UserControls\**" />
    <None Remove="ViewModels\**" />
    <Page Remove="Interfaces\**" />
    <Page Remove="Models\**" />
    <Page Remove="Themes\**" />
    <Page Remove="UserControls\**" />
    <Page Remove="ViewModels\**" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Views\MouseView.xaml.cs" />
  </ItemGroup>

  <ItemGroup>
    <Page Remove="Views\MouseView.xaml" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="DCF.UX.WPF" Version="2.3.14.3" />
    <PackageReference Include="Dell.UCA.ThickClient.Interfaces" Version="4.3.18.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DDPM.UI.Common\DDPM.UI.Common.csproj" />
    <ProjectReference Include="..\DDPM.UI.Module.ButtonSettings\DDPM.UI.Module.ButtonSettings.csproj" />
    <ProjectReference Include="..\DDPM.UI.Module.MouseSettings\DDPM.UI.Module.MouseSettings.csproj" />
    <ProjectReference Include="..\DDPM.UI.Plugin.Common\DDPM.UI.Plugin.Common.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="DDPM.SA.Common">
      <HintPath>..\CommonDll\DDPM.SA.Common.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
