<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows10.0.17763.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Dell.TechHub.Settings" Version="1.5.7.1" />
    <PackageReference Include="Dell.UnifiedAgent.Client" Version="1.4.3.1" />
    <PackageReference Include="DellClientFramework" Version="6.4.11.2" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="DDPM.RemoteManagement.Common">
      <HintPath>..\CommonDll\DDPM.RemoteManagement.Common.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
