<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <Platforms>AnyCPU;x64;ARM64</Platforms>
	  <Version>2.0.0.5</Version>
	  <OutputType>Library</OutputType>
	  <BaseOutputPath>..\..\bin\CommonDll</BaseOutputPath>
	  <Configurations>Debug;Release;Debug_NKVM</Configurations>
  </PropertyGroup>

  <ItemGroup>   
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="WinCopies.WindowsAPICodePack.Shell" Version="2.12.0.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Common\DDPM.SA.Common\DDPM.SA.Common.csproj" />
   
    
  </ItemGroup>
	<Target Name="PostBuild" AfterTargets="PostBuildEvent">
		<Exec Command="xcopy &quot;$(ProjectDir)$(OutDir)*.*&quot; &quot;$(SolutionDir)..\DDPM.UI\CommonDll\&quot; /Y /S /Q" />
	</Target>


</Project>
