<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <Platforms>AnyCPU;x64;ARM64</Platforms>
	  <Version>2.0.0.5</Version>
	  <OutputType>Library</OutputType>
	  <BaseOutputPath>..\..\bin\CommonDll</BaseOutputPath>
	  <Configurations>Debug;Release;Debug_NKVM</Configurations>
  </PropertyGroup>

  <ItemGroup>   
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Common\DDPM.SA.Common\DDPM.SA.Common.csproj" />
  </ItemGroup>


</Project>
