<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>	  
	  <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
	  <OutputPath>$(NGAConsoleOutputPath)</OutputPath>
	  <DocumentationFile>$(HelpOutputPath)\Dell.UCA.BaseClientCore.xml</DocumentationFile>
	  <SignAssembly>True</SignAssembly>
	  <AssemblyOriginatorKeyFile>DUCABaseClientCore.snk</AssemblyOriginatorKeyFile>
	  <UseWPF>True</UseWPF>
	  <AssemblyName>Dell.UCA.BaseClientCore</AssemblyName>
      <ImplicitUsings>enable</ImplicitUsings>     
  </PropertyGroup>

	<ItemGroup>
		<PackageReference Include="DCF.Security" Version="2.4.2.1" />
		<PackageReference Include="DCF.UX.WPF" Version="2.2.4.1" />
	</ItemGroup>

</Project>
