<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
		<OutputPath>..\bin</OutputPath>
		<SignAssembly>True</SignAssembly>
		<AssemblyOriginatorKeyFile>NGAThickClientInterfaces.snk</AssemblyOriginatorKeyFile>
		<UseWPF>True</UseWPF>
		<AssemblyName>Dell.UCA.ThickClient.Interfaces</AssemblyName>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\NGA.Common\NGA.Common.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="DCF.UX.WPF" Version="2.3.14.3" />
	</ItemGroup>
	
</Project>