<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MessagePack" Version="2.5.192" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.5.0" />
    <PackageReference Include="NUnit" Version="3.13.3" />
    <PackageReference Include="NUnit.Analyzers" Version="3.6.1" />
    <PackageReference Include="NUnit3TestAdapter" Version="4.4.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Common\ColorApp\DDPM.ColorApp.csproj" />
    <ProjectReference Include="..\..\Common\DDPM.SA.Common\DDPM.SA.Common.csproj" />
    <ProjectReference Include="..\..\Common\VcpCore.Common\VcpCore.Common.csproj" />
    <ProjectReference Include="..\..\Common\VcpCore.Interfaces\VcpCore.Interfaces.csproj" />
    <ProjectReference Include="..\..\Plugins\DDPM.SA.Plugins.User.ColorPreset\DDPM.SA.Plugins.User.ColorPreset.csproj" />
    <ProjectReference Include="..\..\Plugins\DDPM.SA.Plugins.User.DisplayManager\DDPM.SA.Plugins.User.DisplayManager.csproj" />
    <ProjectReference Include="..\..\Plugins\DDPM.SA.Plugins.User.DisplayProperties\DDPM.SA.Plugins.User.DisplayProperties.csproj" />
    <ProjectReference Include="..\..\Plugins\VcpCore.Plugins\VcpCore.Plugins.csproj" />
    <ProjectReference Include="..\SA.Plugins.User.DisplayManager.Test\SA.Plugins.User.DisplayManager.Test.csproj" />
    <ProjectReference Include="..\SA.Plugins.User.DisplayProperties.Test\SA.Plugins.User.DisplayProperties.Test.csproj" />
  </ItemGroup>

	<ItemGroup>
		<Reference Include="DdmLibrary">
			<HintPath>..\..\dll\DdmLibrary.dll</HintPath>
		</Reference>
	</ItemGroup>

  <ItemGroup>
    <Using Include="NUnit.Framework" />
  </ItemGroup>

</Project>
