<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
	  <UseWindowsForms>true</UseWindowsForms>
	  <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\DDPM.Easy.Common\DDPM.Easy.Common.csproj" />
    <ProjectReference Include="..\DDPM.SA.Common\DDPM.SA.Common.csproj" />
    <ProjectReference Include="..\Win32Lib\DDPM.Win32Lib.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Page Update="ButtonStyle.xaml">
      <SubType>Designer</SubType>
    </Page>
    <Page Update="ComboBoxStyle.xaml">
      <SubType>Designer</SubType>
    </Page>
  </ItemGroup>

</Project>
