//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDPM.SA.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DDPM.SA.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device connected.
        /// </summary>
        internal static string A0_Device_connected {
            get {
                return ResourceManager.GetString("A0_Device_connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firmware update started.
        /// </summary>
        internal static string A1_Firmware_update_started {
            get {
                return ResourceManager.GetString("A1_Firmware_update_started", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firmware update successful.
        /// </summary>
        internal static string A2_Firmware_update_successful {
            get {
                return ResourceManager.GetString("A2_Firmware_update_successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AI Auto-Framing.
        /// </summary>
        internal static string AI_Auto_Framing {
            get {
                return ResourceManager.GetString("AI_Auto_Framing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dell Display and Peripheral Manager.
        /// </summary>
        internal static string App_Name {
            get {
                return ResourceManager.GetString("App_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrange Windows.
        /// </summary>
        internal static string Arrange_Windows {
            get {
                return ResourceManager.GetString("Arrange_Windows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Brightness is currently enabled.Do you wish to override it?.
        /// </summary>
        internal static string Auto_Brightness_is_currently_enabled {
            get {
                return ResourceManager.GetString("Auto_Brightness_is_currently_enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto-framing.
        /// </summary>
        internal static string Auto_framing {
            get {
                return ResourceManager.GetString("Auto_framing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battery Low.
        /// </summary>
        internal static string Battery_Low {
            get {
                return ResourceManager.GetString("Battery_Low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CA check fail.
        /// </summary>
        internal static string CA_check_fail {
            get {
                return ResourceManager.GetString("CA_check_fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to can be updated to.
        /// </summary>
        internal static string can_be_updated_to {
            get {
                return ResourceManager.GetString("can_be_updated_to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel_0 {
            get {
                return ResourceManager.GetString("Cancel_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caps Lock On.
        /// </summary>
        internal static string Caps_Lock_On {
            get {
                return ResourceManager.GetString("Caps_Lock_On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collaboration controls are not available during multiple conference calls.
        /// </summary>
        internal static string CollabMultipleCalls {
            get {
                return ResourceManager.GetString("CollabMultipleCalls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ComfortView.
        /// </summary>
        internal static string ComfortView_0 {
            get {
                return ResourceManager.GetString("ComfortView_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cool.
        /// </summary>
        internal static string Cool_0 {
            get {
                return ResourceManager.GetString("Cool_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom 1.
        /// </summary>
        internal static string Custom_1 {
            get {
                return ResourceManager.GetString("Custom_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom 2.
        /// </summary>
        internal static string Custom_2 {
            get {
                return ResourceManager.GetString("Custom_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom 3.
        /// </summary>
        internal static string Custom_3 {
            get {
                return ResourceManager.GetString("Custom_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Color.
        /// </summary>
        internal static string Custom_Color {
            get {
                return ResourceManager.GetString("Custom_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Color HDR.
        /// </summary>
        internal static string Custom_Color_HDR {
            get {
                return ResourceManager.GetString("Custom_Color_HDR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom layout.
        /// </summary>
        internal static string Custom_layout {
            get {
                return ResourceManager.GetString("Custom_layout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DDPM will reopen soon after update.
        /// </summary>
        internal static string DDPM_will_reopen_soon_after_update {
            get {
                return ResourceManager.GetString("DDPM_will_reopen_soon_after_update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        internal static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defer.
        /// </summary>
        internal static string Defer {
            get {
                return ResourceManager.GetString("Defer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delay.
        /// </summary>
        internal static string Delay {
            get {
                return ResourceManager.GetString("Delay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dell Display and Peripheral Manager.
        /// </summary>
        internal static string Dell_Display_and_Peripheral_Manager {
            get {
                return ResourceManager.GetString("Dell_Display_and_Peripheral_Manager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desktop.
        /// </summary>
        internal static string Desktop_0 {
            get {
                return ResourceManager.GetString("Desktop_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firmware update was unsuccessful due to a firmware utility package issue. The file may be corrupted..
        /// </summary>
        internal static string Display_FWU_Error_1 {
            get {
                return ResourceManager.GetString("Display_FWU_Error_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Another instance of the Firmware Update utility may be running. Close one instance of the utility to proceed..
        /// </summary>
        internal static string Display_FWU_Error_10 {
            get {
                return ResourceManager.GetString("Display_FWU_Error_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Another instance of the Firmware Update utility may be running. Close one instance of the utility to proceed..
        /// </summary>
        internal static string Display_FWU_Error_12 {
            get {
                return ResourceManager.GetString("Display_FWU_Error_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The update may take up to xx minutes. Keep your monitor powered on and connected during the update..
        /// </summary>
        internal static string Display_FWU_Error_201 {
            get {
                return ResourceManager.GetString("Display_FWU_Error_201", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The firmware update encountered an error. To resolve this issue, disconnect and reconnect the USB cable and power cycle the monitor. Then, retry the firmware update..
        /// </summary>
        internal static string Display_FWU_Error_3 {
            get {
                return ResourceManager.GetString("Display_FWU_Error_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The firmware update encountered an error. To resolve this issue, disconnect and reconnect the USB cable and  power cycle the monitor. Then, retry the firmware update..
        /// </summary>
        internal static string Display_FWU_Error_5 {
            get {
                return ResourceManager.GetString("Display_FWU_Error_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The firmware version detected on your monitor is not an official release..
        /// </summary>
        internal static string Display_FWU_Error_501 {
            get {
                return ResourceManager.GetString("Display_FWU_Error_501", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The firmware update encountered an error. To resolve this issue, disconnect and reconnect the USB cable and power cycle the monitor. Then, retry the firmware update..
        /// </summary>
        internal static string Display_FWU_Error_61 {
            get {
                return ResourceManager.GetString("Display_FWU_Error_61", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The firmware update was unsuccessful. The firmware code has been erased, and verification of the firmware code failed..
        /// </summary>
        internal static string Display_FWU_Error_7 {
            get {
                return ResourceManager.GetString("Display_FWU_Error_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your monitor’s firmware is the latest version..
        /// </summary>
        internal static string Display_FWU_Error_9 {
            get {
                return ResourceManager.GetString("Display_FWU_Error_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The firmware update was unsuccesful..
        /// </summary>
        internal static string Display_FWU_Error_Other {
            get {
                return ResourceManager.GetString("Display_FWU_Error_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display P3.
        /// </summary>
        internal static string Display_P3 {
            get {
                return ResourceManager.GetString("Display_P3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dock FW info.
        /// </summary>
        internal static string Dock_FW_info {
            get {
                return ResourceManager.GetString("Dock_FW_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dock FW is being loaded. Do not disconnect the dock..
        /// </summary>
        internal static string Dock_FW_is_being_loaded {
            get {
                return ResourceManager.GetString("Dock_FW_is_being_loaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dock FW is loaded. Disconnect dock for completing FW application and reconnect dock after 1 min..
        /// </summary>
        internal static string Dock_FW_is_loaded {
            get {
                return ResourceManager.GetString("Dock_FW_is_loaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dock FW is loaded successful. Disconnect dock for completing FW application and reconnect dock after 1 min..
        /// </summary>
        internal static string Dock_FW_is_loaded_successful {
            get {
                return ResourceManager.GetString("Dock_FW_is_loaded_successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dock FW loaded failed..
        /// </summary>
        internal static string Dock_FW_loaded_failed {
            get {
                return ResourceManager.GetString("Dock_FW_loaded_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dock UOD FW update info.
        /// </summary>
        internal static string Dock_UOD_FW_update_info {
            get {
                return ResourceManager.GetString("Dock_UOD_FW_update_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading and installing.
        /// </summary>
        internal static string Downloading_and_installing {
            get {
                return ResourceManager.GetString("Downloading_and_installing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USB wireless receiver firmware is unable to support device firmware upgrade.
        /// </summary>
        internal static string E4_USB_wireless_receiver_firmware_is_unable_to_support_device_firmware_upgrade {
            get {
                return ResourceManager.GetString("E4_USB_wireless_receiver_firmware_is_unable_to_support_device_firmware_upgrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjust your current window arrangement, edit the name (if desired), and click “Save”  to store the arrangement..
        /// </summary>
        internal static string EA_MSG_0 {
            get {
                return ResourceManager.GetString("EA_MSG_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are Easy Memory profiles associated to this custom layout.\nSaving this custom layout will update the layout for all the associated profiles.\nDo you want to save the layout?.
        /// </summary>
        internal static string EABroker_updateToEmProfilePrompt {
            get {
                return ResourceManager.GetString("EABroker_updateToEmProfilePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Easy Memory.
        /// </summary>
        internal static string Easy_Memory {
            get {
                return ResourceManager.GetString("Easy_Memory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The same monitor is detected, do you want to import settings for.
        /// </summary>
        internal static string Export_MSG_0 {
            get {
                return ResourceManager.GetString("Export_MSG_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to open application.
        /// </summary>
        internal static string Failed_to_open_application {
            get {
                return ResourceManager.GetString("Failed_to_open_application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field of View.
        /// </summary>
        internal static string Field_of_View {
            get {
                return ResourceManager.GetString("Field_of_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firmware Update.
        /// </summary>
        internal static string Firmware_Update {
            get {
                return ResourceManager.GetString("Firmware_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firmware update for [XXXXXX] aborted. Ensure only one device of same model is connected to system..
        /// </summary>
        internal static string Firmware_update_aborted_same_model_is_connected {
            get {
                return ResourceManager.GetString("Firmware_update_aborted_same_model_is_connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firmware update for [XXXXXX] in progress. Fail to abort..
        /// </summary>
        internal static string Firmware_update_in_progress_Fail_to_abort {
            get {
                return ResourceManager.GetString("Firmware_update_in_progress_Fail_to_abort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firmware update for [XXXXXX] was unsuccessful.
        /// </summary>
        internal static string Firmware_update_unsuccessful {
            get {
                return ResourceManager.GetString("Firmware_update_unsuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firmware updated..
        /// </summary>
        internal static string Firmware_updated {
            get {
                return ResourceManager.GetString("Firmware_updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FPS Game.
        /// </summary>
        internal static string FPS_Game {
            get {
                return ResourceManager.GetString("FPS_Game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FW info.
        /// </summary>
        internal static string FW_info {
            get {
                return ResourceManager.GetString("FW_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FW is being installed. Do not disconnect the device..
        /// </summary>
        internal static string FW_is_being_Installing {
            get {
                return ResourceManager.GetString("FW_is_being_Installing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game.
        /// </summary>
        internal static string Game_0 {
            get {
                return ResourceManager.GetString("Game_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game1.
        /// </summary>
        internal static string Game_1 {
            get {
                return ResourceManager.GetString("Game_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game2.
        /// </summary>
        internal static string Game_2 {
            get {
                return ResourceManager.GetString("Game_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game3.
        /// </summary>
        internal static string Game_3 {
            get {
                return ResourceManager.GetString("Game_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game HDR.
        /// </summary>
        internal static string Game_HDR {
            get {
                return ResourceManager.GetString("Game_HDR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to Widget Settings.
        /// </summary>
        internal static string Go_to_Widget_Settings {
            get {
                return ResourceManager.GetString("Go_to_Widget_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HDR Peak 1000.
        /// </summary>
        internal static string HDR_Peak_1000 {
            get {
                return ResourceManager.GetString("HDR_Peak_1000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The default ICC profile is for Smart HDR. We are not able to change color preset in the.
        /// </summary>
        internal static string ICC_notification_NonSmartHDR {
            get {
                return ResourceManager.GetString("ICC_notification_NonSmartHDR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The default ICC profile is not suitable for Smart HDR. We are not able to change color preset in the.
        /// </summary>
        internal static string ICC_notification_SmartHDR {
            get {
                return ResourceManager.GetString("ICC_notification_SmartHDR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The same monitor is detected, do you want to import settings for %1?.
        /// </summary>
        internal static string ImpExp_Message_0 {
            get {
                return ResourceManager.GetString("ImpExp_Message.0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing.
        /// </summary>
        internal static string Installing {
            get {
                return ResourceManager.GetString("Installing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid ID. Please provide a valid action ID..
        /// </summary>
        internal static string Invalid_ID {
            get {
                return ResourceManager.GetString("Invalid_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is muted.
        /// </summary>
        internal static string is_muted {
            get {
                return ResourceManager.GetString("is_muted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is unmuted.
        /// </summary>
        internal static string is_Unmuted {
            get {
                return ResourceManager.GetString("is_Unmuted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move or click the target mouse’s left button twice.
        /// </summary>
        internal static string M1_Please_double_click_mouse_left_button_to_start_firmware_update {
            get {
                return ResourceManager.GetString("M1_Please_double_click_mouse_left_button_to_start_firmware_update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press “U” key twice to activate firmware update of target keyboard.
        /// </summary>
        internal static string M2_Please_press_key_on_keyboard_to_start_firmware_update {
            get {
                return ResourceManager.GetString("M2_Please_press_key_on_keyboard_to_start_firmware_update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metro.
        /// </summary>
        internal static string Metro_0 {
            get {
                return ResourceManager.GetString("Metro_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movie.
        /// </summary>
        internal static string Movie_0 {
            get {
                return ResourceManager.GetString("Movie_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movie HDR.
        /// </summary>
        internal static string Movie_HDR {
            get {
                return ResourceManager.GetString("Movie_HDR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multimedia.
        /// </summary>
        internal static string Multimedia_0 {
            get {
                return ResourceManager.GetString("Multimedia_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple docks are detected. Keep only one dock connected to prevent damage to your docks..
        /// </summary>
        internal static string Multiple_docks_are_detected {
            get {
                return ResourceManager.GetString("Multiple_docks_are_detected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple docks are detected. Keep only one dock connected to prevent damage to your dock(s)..
        /// </summary>
        internal static string Multiple_docks_are_detected2 {
            get {
                return ResourceManager.GetString("Multiple_docks_are_detected2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple docks detected. Keep only one dock connected to prevent damage to your docks. Restart the PC, then connect only one dock..
        /// </summary>
        internal static string Multiple_docks_are_detected3 {
            get {
                return ResourceManager.GetString("Multiple_docks_are_detected3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiscreen Match.
        /// </summary>
        internal static string Multiscreen_Match {
            get {
                return ResourceManager.GetString("Multiscreen_Match", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Native.
        /// </summary>
        internal static string Native_0 {
            get {
                return ResourceManager.GetString("Native_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nature.
        /// </summary>
        internal static string Nature_0 {
            get {
                return ResourceManager.GetString("Nature_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network fail.
        /// </summary>
        internal static string Network_fail {
            get {
                return ResourceManager.GetString("Network_fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no updates available..
        /// </summary>
        internal static string no_updates_available {
            get {
                return ResourceManager.GetString("no_updates_available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Num Lock Off.
        /// </summary>
        internal static string Num_Lock_Off {
            get {
                return ResourceManager.GetString("Num_Lock_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Num Lock On.
        /// </summary>
        internal static string Num_Lock_On {
            get {
                return ResourceManager.GetString("Num_Lock_On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OFF.
        /// </summary>
        internal static string OFF {
            get {
                return ResourceManager.GetString("OFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        internal static string Off_0 {
            get {
                return ResourceManager.GetString("Off_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ON.
        /// </summary>
        internal static string ON {
            get {
                return ResourceManager.GetString("ON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paper.
        /// </summary>
        internal static string Paper_0 {
            get {
                return ResourceManager.GetString("Paper_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Presence detection sensor is covered.
        /// </summary>
        internal static string Presence_detection_sensor_is_covered {
            get {
                return ResourceManager.GetString("Presence_detection_sensor_is_covered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Presets.
        /// </summary>
        internal static string Presets {
            get {
                return ResourceManager.GetString("Presets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Presets Disabled.
        /// </summary>
        internal static string Presets_Disabled {
            get {
                return ResourceManager.GetString("Presets_Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing.
        /// </summary>
        internal static string Processing {
            get {
                return ResourceManager.GetString("Processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To access Quick Settings Widget again, press and hold [Alt + Z] on your keyboard..
        /// </summary>
        internal static string QAM_OSD_Msg {
            get {
                return ResourceManager.GetString("QAM_OSD_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference.
        /// </summary>
        internal static string Reference_0 {
            get {
                return ResourceManager.GetString("Reference_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RPG Game.
        /// </summary>
        internal static string RPG_Game {
            get {
                return ResourceManager.GetString("RPG_Game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RTS Game.
        /// </summary>
        internal static string RTS_Game {
            get {
                return ResourceManager.GetString("RTS_Game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save_0 {
            get {
                return ResourceManager.GetString("Save_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scroll Lock Off.
        /// </summary>
        internal static string Scroll_Lock_Off {
            get {
                return ResourceManager.GetString("Scroll_Lock_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scroll Lock On.
        /// </summary>
        internal static string Scroll_Lock_On {
            get {
                return ResourceManager.GetString("Scroll_Lock_On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to s.
        /// </summary>
        internal static string Seconds {
            get {
                return ResourceManager.GetString("Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service not running. Try again.
        /// </summary>
        internal static string Service_not_running_Try_again {
            get {
                return ResourceManager.GetString("Service_not_running_Try_again", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smooth.
        /// </summary>
        internal static string Smooth {
            get {
                return ResourceManager.GetString("Smooth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Software Update.
        /// </summary>
        internal static string Software_Update {
            get {
                return ResourceManager.GetString("Software_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Software update failed.
        /// </summary>
        internal static string Software_update_failed {
            get {
                return ResourceManager.GetString("Software_update_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Software update successful.
        /// </summary>
        internal static string Software_update_successful {
            get {
                return ResourceManager.GetString("Software_update_successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Software update unsuccessful..
        /// </summary>
        internal static string Software_update_unsuccessful {
            get {
                return ResourceManager.GetString("Software_update_unsuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sport.
        /// </summary>
        internal static string Sport_0 {
            get {
                return ResourceManager.GetString("Sport_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SPORTS Game.
        /// </summary>
        internal static string SPORTS_Game {
            get {
                return ResourceManager.GetString("SPORTS_Game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard.
        /// </summary>
        internal static string Standard_0 {
            get {
                return ResourceManager.GetString("Standard_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard HDR.
        /// </summary>
        internal static string Standard_HDR {
            get {
                return ResourceManager.GetString("Standard_HDR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SW info.
        /// </summary>
        internal static string SW_info {
            get {
                return ResourceManager.GetString("SW_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        internal static string Text_0 {
            get {
                return ResourceManager.GetString("Text_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout.
        /// </summary>
        internal static string Timeout {
            get {
                return ResourceManager.GetString("Timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout error.
        /// </summary>
        internal static string Timeout_error {
            get {
                return ResourceManager.GetString("Timeout_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to detect target device.
        /// </summary>
        internal static string Unable_to_detect_target_device {
            get {
                return ResourceManager.GetString("Unable_to_detect_target_device", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to synchronize the corresponding ICC profile for.
        /// </summary>
        internal static string Unable_to_synchronize_the_corresponding_ICC_profile {
            get {
                return ResourceManager.GetString("Unable_to_synchronize_the_corresponding_ICC_profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UOD update completed..
        /// </summary>
        internal static string UOD_update_completed {
            get {
                return ResourceManager.GetString("UOD_update_completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UOD update fail..
        /// </summary>
        internal static string UOD_update_fail {
            get {
                return ResourceManager.GetString("UOD_update_fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update may take an estimated 10 to 30 minutes to complete, depending on your monitor model and setup (for example, type of connection). It may take longer if you are updating multiple monitors of the same model. Don’t power off your display or disconnect cables while the update is downloading..
        /// </summary>
        internal static string Update_Display_Alert {
            get {
                return ResourceManager.GetString("Update_Display_Alert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The update may take up to [XXXXXX] minutes. Keep the device powered on and connected during this time..
        /// </summary>
        internal static string Update_Display_Alert_2 {
            get {
                return ResourceManager.GetString("Update_Display_Alert_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please connect your monitor using the USB upstream port to avoid errors during the firmware update process.
        /// </summary>
        internal static string Update_Display_Alert_3 {
            get {
                return ResourceManager.GetString("Update_Display_Alert_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update download cancel, because PC battery too low..
        /// </summary>
        internal static string update_download_cancel {
            get {
                return ResourceManager.GetString("update_download_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update failed.
        /// </summary>
        internal static string Update_failed {
            get {
                return ResourceManager.GetString("Update_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firmware of [XXXXXX] failed to update.
        /// </summary>
        internal static string Update_failed_body {
            get {
                return ResourceManager.GetString("Update_failed_body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update for [XXXXXX] failed due to network error. Try again..
        /// </summary>
        internal static string Update_failed_due_to_network_error {
            get {
                return ResourceManager.GetString("Update_failed_due_to_network_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update failed with unknown error.
        /// </summary>
        internal static string update_failed_with_unknown_error {
            get {
                return ResourceManager.GetString("update_failed_with_unknown_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firmware update in progress.
        /// </summary>
        internal static string Update_in_progress {
            get {
                return ResourceManager.GetString("Update_in_progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [XXXXXX] may be intermittently available. Do not disconnect the device during the update..
        /// </summary>
        internal static string Update_in_progress_body {
            get {
                return ResourceManager.GetString("Update_in_progress_body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update successful.
        /// </summary>
        internal static string Update_successful {
            get {
                return ResourceManager.GetString("Update_successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firmware of [XXXXXX] updated successfully.
        /// </summary>
        internal static string Update_successful_body {
            get {
                return ResourceManager.GetString("Update_successful_body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update available.
        /// </summary>
        internal static string UpdateAvailable {
            get {
                return ResourceManager.GetString("UpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device and/or application will be updated. Device and/or application may be intermittently available. Do not disconnect the device during the update..
        /// </summary>
        internal static string UpdateAvailable_Info {
            get {
                return ResourceManager.GetString("UpdateAvailable_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update now.
        /// </summary>
        internal static string UpdateNow {
            get {
                return ResourceManager.GetString("UpdateNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not power down system until updates are complete.
        /// </summary>
        internal static string UpdateProgressMsg {
            get {
                return ResourceManager.GetString("UpdateProgressMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updates info.
        /// </summary>
        internal static string Updates_info {
            get {
                return ResourceManager.GetString("Updates_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update will be applied.
        /// </summary>
        internal static string UpdateWillBeApplied {
            get {
                return ResourceManager.GetString("UpdateWillBeApplied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device and/or application will be updated. Device and/or application may be intermittently available. Do not disconnect the device during the update..
        /// </summary>
        internal static string UpdateWillBeApplied_Info {
            get {
                return ResourceManager.GetString("UpdateWillBeApplied_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating firmware. Do not remove or power off the device. Leave the device undisturbed..
        /// </summary>
        internal static string Updating_firmware_Do_not_remove_or_power_off_the_device_Leave_the_device_undisturbed {
            get {
                return ResourceManager.GetString("Updating_firmware_Do_not_remove_or_power_off_the_device_Leave_the_device_undistur" +
                        "bed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating Software. Do not power off this PC..
        /// </summary>
        internal static string Updating_Software_Do_not_power_off_this_PC {
            get {
                return ResourceManager.GetString("Updating_Software_Do_not_power_off_this_PC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USB wireless receiver firmware is unable to support device firmware upgrade.
        /// </summary>
        internal static string USB_wireless_receiver_firmware_is_unable_to_support_device_firmware_upgrade {
            get {
                return ResourceManager.GetString("USB_wireless_receiver_firmware_is_unable_to_support_device_firmware_upgrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User 1.
        /// </summary>
        internal static string User_1 {
            get {
                return ResourceManager.GetString("User_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User 2.
        /// </summary>
        internal static string User_2 {
            get {
                return ResourceManager.GetString("User_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User 3.
        /// </summary>
        internal static string User_3 {
            get {
                return ResourceManager.GetString("User_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User aborted firmware update for [XXXXXX].
        /// </summary>
        internal static string User_aborted_firmware_update {
            get {
                return ResourceManager.GetString("User_aborted_firmware_update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vibrant.
        /// </summary>
        internal static string Vibrant {
            get {
                return ResourceManager.GetString("Vibrant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vivid HDR.
        /// </summary>
        internal static string Vivid_HDR {
            get {
                return ResourceManager.GetString("Vivid_HDR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Walk Away Lock.
        /// </summary>
        internal static string Walk_Away_Lock {
            get {
                return ResourceManager.GetString("Walk_Away_Lock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warm.
        /// </summary>
        internal static string Warm {
            get {
                return ResourceManager.GetString("Warm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warm.
        /// </summary>
        internal static string Warm_0 {
            get {
                return ResourceManager.GetString("Warm_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utilizes intelligent scene analysis and facial tracking to zoom and pan the view when you move.
        /// </summary>
        internal static string WebCameraSettings_2 {
            get {
                return ResourceManager.GetString("WebCameraSettings.2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to will be updated to .
        /// </summary>
        internal static string will_be_updated_to {
            get {
                return ResourceManager.GetString("will_be_updated_to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom.
        /// </summary>
        internal static string Zoom {
            get {
                return ResourceManager.GetString("Zoom", resourceCulture);
            }
        }
    }
}
