//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDPM.SA.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DDPM.SA.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device connected.
        /// </summary>
        internal static string A0_Device_connected {
            get {
                return ResourceManager.GetString("A0_Device_connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firmware update started.
        /// </summary>
        internal static string A1_Firmware_update_started {
            get {
                return ResourceManager.GetString("A1_Firmware_update_started", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firmware update successful.
        /// </summary>
        internal static string A2_Firmware_update_successful {
            get {
                return ResourceManager.GetString("A2_Firmware_update_successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AI Auto-Framing.
        /// </summary>
        internal static string AI_Auto_Framing {
            get {
                return ResourceManager.GetString("AI_Auto_Framing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Brightness is currently enabled.Do you wish to override it?.
        /// </summary>
        internal static string Auto_Brightness_is_currently_enabled {
            get {
                return ResourceManager.GetString("Auto_Brightness_is_currently_enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto-framing.
        /// </summary>
        internal static string Auto_framing {
            get {
                return ResourceManager.GetString("Auto_framing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CA check fail.
        /// </summary>
        internal static string CA_check_fail {
            get {
                return ResourceManager.GetString("CA_check_fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to can be updated to.
        /// </summary>
        internal static string can_be_updated_to {
            get {
                return ResourceManager.GetString("can_be_updated_to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DDPM will reopen soon after update.
        /// </summary>
        internal static string DDPM_will_reopen_soon_after_update {
            get {
                return ResourceManager.GetString("DDPM_will_reopen_soon_after_update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        internal static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defer.
        /// </summary>
        internal static string Defer {
            get {
                return ResourceManager.GetString("Defer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delay.
        /// </summary>
        internal static string Delay {
            get {
                return ResourceManager.GetString("Delay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dock FW info.
        /// </summary>
        internal static string Dock_FW_info {
            get {
                return ResourceManager.GetString("Dock_FW_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dock FW is being loaded. Do not disconnect the dock..
        /// </summary>
        internal static string Dock_FW_is_being_loaded {
            get {
                return ResourceManager.GetString("Dock_FW_is_being_loaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dock FW is loaded. Disconnect dock for completing FW application and reconnect dock after 1 min..
        /// </summary>
        internal static string Dock_FW_is_loaded {
            get {
                return ResourceManager.GetString("Dock_FW_is_loaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dock FW is loaded successful. Disconnect dock for completing FW application and reconnect dock after 1 min..
        /// </summary>
        internal static string Dock_FW_is_loaded_successful {
            get {
                return ResourceManager.GetString("Dock_FW_is_loaded_successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dock FW loaded failed..
        /// </summary>
        internal static string Dock_FW_loaded_failed {
            get {
                return ResourceManager.GetString("Dock_FW_loaded_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dock UOD FW update info.
        /// </summary>
        internal static string Dock_UOD_FW_update_info {
            get {
                return ResourceManager.GetString("Dock_UOD_FW_update_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading and installing.
        /// </summary>
        internal static string Downloading_and_installing {
            get {
                return ResourceManager.GetString("Downloading_and_installing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USB wireless receiver firmware is unable to support device firmware upgrade.
        /// </summary>
        internal static string E4_USB_wireless_receiver_firmware_is_unable_to_support_device_firmware_upgrade {
            get {
                return ResourceManager.GetString("E4_USB_wireless_receiver_firmware_is_unable_to_support_device_firmware_upgrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to open application.
        /// </summary>
        internal static string Failed_to_open_application {
            get {
                return ResourceManager.GetString("Failed_to_open_application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field of View.
        /// </summary>
        internal static string Field_of_View {
            get {
                return ResourceManager.GetString("Field_of_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firmware Update.
        /// </summary>
        internal static string Firmware_Update {
            get {
                return ResourceManager.GetString("Firmware_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firmware update unsuccessful..
        /// </summary>
        internal static string Firmware_update_unsuccessful {
            get {
                return ResourceManager.GetString("Firmware_update_unsuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FW info.
        /// </summary>
        internal static string FW_info {
            get {
                return ResourceManager.GetString("FW_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FW is being Installing. Do not disconnect the device..
        /// </summary>
        internal static string FW_is_being_Installing {
            get {
                return ResourceManager.GetString("FW_is_being_Installing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing.
        /// </summary>
        internal static string Installing {
            get {
                return ResourceManager.GetString("Installing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid ID. Please provide a valid action ID..
        /// </summary>
        internal static string Invalid_ID {
            get {
                return ResourceManager.GetString("Invalid_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please double click mouse left button to start firmware update.
        /// </summary>
        internal static string M1_Please_double_click_mouse_left_button_to_start_firmware_update {
            get {
                return ResourceManager.GetString("M1_Please_double_click_mouse_left_button_to_start_firmware_update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please press \&quot;U\&quot; key on keyboard to start firmware update.
        /// </summary>
        internal static string M2_Please_press_key_on_keyboard_to_start_firmware_update {
            get {
                return ResourceManager.GetString("M2_Please_press_key_on_keyboard_to_start_firmware_update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple docks are detected. Keep only one dock connected to prevent damage to your docks..
        /// </summary>
        internal static string Multiple_docks_are_detected {
            get {
                return ResourceManager.GetString("Multiple_docks_are_detected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network fail.
        /// </summary>
        internal static string Network_fail {
            get {
                return ResourceManager.GetString("Network_fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no updates available..
        /// </summary>
        internal static string no_updates_available {
            get {
                return ResourceManager.GetString("no_updates_available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OFF.
        /// </summary>
        internal static string OFF {
            get {
                return ResourceManager.GetString("OFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ON.
        /// </summary>
        internal static string ON {
            get {
                return ResourceManager.GetString("ON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Presets.
        /// </summary>
        internal static string Presets {
            get {
                return ResourceManager.GetString("Presets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing.
        /// </summary>
        internal static string Processing {
            get {
                return ResourceManager.GetString("Processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service not running. Try again.
        /// </summary>
        internal static string Service_not_running_Try_again {
            get {
                return ResourceManager.GetString("Service_not_running_Try_again", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smooth.
        /// </summary>
        internal static string Smooth {
            get {
                return ResourceManager.GetString("Smooth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Software Update.
        /// </summary>
        internal static string Software_Update {
            get {
                return ResourceManager.GetString("Software_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Software update unsuccessful..
        /// </summary>
        internal static string Software_update_unsuccessful {
            get {
                return ResourceManager.GetString("Software_update_unsuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SW info.
        /// </summary>
        internal static string SW_info {
            get {
                return ResourceManager.GetString("SW_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout.
        /// </summary>
        internal static string Timeout {
            get {
                return ResourceManager.GetString("Timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout error.
        /// </summary>
        internal static string Timeout_error {
            get {
                return ResourceManager.GetString("Timeout_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to detect target device.
        /// </summary>
        internal static string Unable_to_detect_target_device {
            get {
                return ResourceManager.GetString("Unable_to_detect_target_device", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UOD update completed..
        /// </summary>
        internal static string UOD_update_completed {
            get {
                return ResourceManager.GetString("UOD_update_completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UOD update fail..
        /// </summary>
        internal static string UOD_update_fail {
            get {
                return ResourceManager.GetString("UOD_update_fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update download cancel, because PC battery too low..
        /// </summary>
        internal static string update_download_cancel {
            get {
                return ResourceManager.GetString("update_download_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update failed due to network error. Try again..
        /// </summary>
        internal static string Update_failed_due_to_network_error {
            get {
                return ResourceManager.GetString("Update_failed_due_to_network_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to update failed with unknown error.
        /// </summary>
        internal static string update_failed_with_unknown_error {
            get {
                return ResourceManager.GetString("update_failed_with_unknown_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update available.
        /// </summary>
        internal static string UpdateAvailable {
            get {
                return ResourceManager.GetString("UpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device and/or application will be updated. Device and/or application may be intermittently available. Do not disconnect the device during the update..
        /// </summary>
        internal static string UpdateAvailable_Info {
            get {
                return ResourceManager.GetString("UpdateAvailable_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update now.
        /// </summary>
        internal static string UpdateNow {
            get {
                return ResourceManager.GetString("UpdateNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updates info.
        /// </summary>
        internal static string Updates_info {
            get {
                return ResourceManager.GetString("Updates_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update will be applied.
        /// </summary>
        internal static string UpdateWillBeApplied {
            get {
                return ResourceManager.GetString("UpdateWillBeApplied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device and/or application will be updated. Device and/or application may be intermittently available. Do not disconnect the device during the update..
        /// </summary>
        internal static string UpdateWillBeApplied_Info {
            get {
                return ResourceManager.GetString("UpdateWillBeApplied_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating firmware. Do not remove or power off the device. Leave the device undisturbed.
        /// </summary>
        internal static string Updating_firmware_Do_not_remove_or_power_off_the_device_Leave_the_device_undisturbed {
            get {
                return ResourceManager.GetString("Updating_firmware_Do_not_remove_or_power_off_the_device_Leave_the_device_undistur" +
                        "bed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating Software. Do not power off this PC..
        /// </summary>
        internal static string Updating_Software_Do_not_power_off_this_PC {
            get {
                return ResourceManager.GetString("Updating_Software_Do_not_power_off_this_PC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User aborted firmware update.
        /// </summary>
        internal static string User_aborted_firmware_update {
            get {
                return ResourceManager.GetString("User_aborted_firmware_update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vibrant.
        /// </summary>
        internal static string Vibrant {
            get {
                return ResourceManager.GetString("Vibrant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warm.
        /// </summary>
        internal static string Warm {
            get {
                return ResourceManager.GetString("Warm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to will be updated to .
        /// </summary>
        internal static string will_be_updated_to_ {
            get {
                return ResourceManager.GetString("will_be_updated_to ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom.
        /// </summary>
        internal static string Zoom {
            get {
                return ResourceManager.GetString("Zoom", resourceCulture);
            }
        }
    }
}
