<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
		<OutputPath>..\bin</OutputPath>
		<SignAssembly>false</SignAssembly>
		<Nullable>disable</Nullable>
		<AssemblyName>Dell.UCA.Manager.Interfaces</AssemblyName>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="DellClientFramework" Version="6.4.5.1" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
	</ItemGroup>

	<ItemGroup Condition="'$(TargetFramework)' == 'net472'">
		<PackageReference Include="System.Threading.Tasks.Extensions" Version="4.5.4" />
	</ItemGroup>
</Project>