<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
		<SupportedOSPlatformVersion>10.0.19041.0</SupportedOSPlatformVersion>
		<OutputType>Exe</OutputType>
		<BaseOutputPath>..\bin\$(MSBuildProjectName)\</BaseOutputPath>
		<Platforms>AnyCPU;x64</Platforms>
		<Version>2.0.0.50</Version>
		<Configurations>Debug;Release;Debug_NKVM</Configurations>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Dell.TechHub.Settings" Version="1.5.7.1" />
		<PackageReference Include="Dell.UnifiedAgent.Client" Version="1.4.8.2" />
		<PackageReference Include="MessagePack" Version="2.5.192" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Common\DDPM.SA.Common\DDPM.SA.Common.csproj" />
		<ProjectReference Include="..\Common\DDPM.SA.Obfuscation\DDPM.SA.Obfuscation.csproj" />
	</ItemGroup>

</Project>
