//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NGA.ThickClient {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DDPM.Properties.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M11.9475 5.25C11.7801 3.92998 11.1787 2.70306 10.2378 1.76219C9.29697 0.821322 8.07004 0.219895 6.75003 0.0525C6.50151 0.0179984 6.25093 0.000457859 6.00003 0C4.4809 0.0103651 3.02227 0.596591 1.91848 1.64037C0.814689 2.68416 0.147927 4.10778 0.0527501 5.62395C-0.042427 7.14012 0.441067 8.63595 1.40566 9.80958C2.37025 10.9832 3.74413 11.7472 5.25003 11.9475C5.49854 11.982 5.74912 11.9995 6.00003 12C6.85082 11.9992 7.69172 11.8175 8.46693 11.4669C9.24214 11.1164 9.93393 10.6049 10.4964 9.96659C11.0588 9.3282 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string AddDeviceIconPathData {
            get {
                return ResourceManager.GetString("AddDeviceIconPathData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only one instance of the Console can be active at one time..
        /// </summary>
        public static string strConsoleMultiInstanceError {
            get {
                return ResourceManager.GetString("strConsoleMultiInstanceError", resourceCulture);
            }
        }
    }
}
