//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDPM.UI.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DDPM.UI.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adaptive Light.
        /// </summary>
        internal static string AdaptiveLight {
            get {
                return ResourceManager.GetString("AdaptiveLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Device.
        /// </summary>
        internal static string AddDevice {
            get {
                return ResourceManager.GetString("AddDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display.
        /// </summary>
        internal static string AddDevice_Display {
            get {
                return ResourceManager.GetString("AddDevice.Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dock.
        /// </summary>
        internal static string AddDevice_Dock {
            get {
                return ResourceManager.GetString("AddDevice.Dock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Headset.
        /// </summary>
        internal static string AddDevice_Headset {
            get {
                return ResourceManager.GetString("AddDevice.Headset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyboard\nand Mouse.
        /// </summary>
        internal static string AddDevice_KnM {
            get {
                return ResourceManager.GetString("AddDevice.KnM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string AddDevice_Msg_CancelBtn {
            get {
                return ResourceManager.GetString("AddDevice.Msg.CancelBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pairing may take some time. Do not disconnect your device.
        /// </summary>
        internal static string AddDevice_Msg_WaitingAlert {
            get {
                return ResourceManager.GetString("AddDevice.Msg.WaitingAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding device, please wait....
        /// </summary>
        internal static string AddDevice_Msg_WaitingCap {
            get {
                return ResourceManager.GetString("AddDevice.Msg.WaitingCap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pairing.
        /// </summary>
        internal static string AddDevice_Msg_WaitingMsg {
            get {
                return ResourceManager.GetString("AddDevice.Msg.WaitingMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pen.
        /// </summary>
        internal static string AddDevice_Pen {
            get {
                return ResourceManager.GetString("AddDevice.Pen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speakerphone\nand Soundbar.
        /// </summary>
        internal static string AddDevice_Speaker {
            get {
                return ResourceManager.GetString("AddDevice.Speaker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bluetooth.
        /// </summary>
        internal static string AddDevice_Type_Bluetooth {
            get {
                return ResourceManager.GetString("AddDevice.Type.Bluetooth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        internal static string AddDevice_Type_Other {
            get {
                return ResourceManager.GetString("AddDevice.Type.Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wired.
        /// </summary>
        internal static string AddDevice_Type_Wired {
            get {
                return ResourceManager.GetString("AddDevice.Type.Wired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wireless receiver.
        /// </summary>
        internal static string AddDevice_Type_Wireless {
            get {
                return ResourceManager.GetString("AddDevice.Type.Wireless", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Webcam.
        /// </summary>
        internal static string AddDevice_Webcam {
            get {
                return ResourceManager.GetString("AddDevice.Webcam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analytics.
        /// </summary>
        internal static string Analytics {
            get {
                return ResourceManager.GetString("Analytics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analytics.
        /// </summary>
        internal static string Analytics_0 {
            get {
                return ResourceManager.GetString("Analytics.0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help Dell improve its products and services automatically sending diagnostics and usage data..
        /// </summary>
        internal static string Analytics_1 {
            get {
                return ResourceManager.GetString("Analytics.1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dell&apos;s Privacy Policy.
        /// </summary>
        internal static string Analytics_2 {
            get {
                return ResourceManager.GetString("Analytics.2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help Dell improve its products and services automatically.
        /// </summary>
        internal static string Analytics_3 {
            get {
                return ResourceManager.GetString("Analytics.3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display.
        /// </summary>
        internal static string Display {
            get {
                return ResourceManager.GetString("Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Settings.
        /// </summary>
        internal static string DisplaySettings {
            get {
                return ResourceManager.GetString("DisplaySettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Easy Arrange.
        /// </summary>
        internal static string EasyArrange {
            get {
                return ResourceManager.GetString("EasyArrange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firmware Version.
        /// </summary>
        internal static string FirmwareVersion {
            get {
                return ResourceManager.GetString("FirmwareVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gaming.
        /// </summary>
        internal static string Gaming {
            get {
                return ResourceManager.GetString("Gaming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Source.
        /// </summary>
        internal static string InputSource {
            get {
                return ResourceManager.GetString("InputSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KVM.
        /// </summary>
        internal static string KVM {
            get {
                return ResourceManager.GetString("KVM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual.
        /// </summary>
        internal static string Manual {
            get {
                return ResourceManager.GetString("Manual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufactured.
        /// </summary>
        internal static string ManufactureMonth {
            get {
                return ResourceManager.GetString("ManufactureMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OFF.
        /// </summary>
        internal static string Off {
            get {
                return ResourceManager.GetString("Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ON.
        /// </summary>
        internal static string On {
            get {
                return ResourceManager.GetString("On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick Settings.
        /// </summary>
        internal static string QuickSettings {
            get {
                return ResourceManager.GetString("QuickSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore to default.
        /// </summary>
        internal static string RestoreToDefault {
            get {
                return ResourceManager.GetString("RestoreToDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Tag.
        /// </summary>
        internal static string ServiceTag {
            get {
                return ResourceManager.GetString("ServiceTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unpair.
        /// </summary>
        internal static string Unpair {
            get {
                return ResourceManager.GetString("Unpair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updates.
        /// </summary>
        internal static string Updates {
            get {
                return ResourceManager.GetString("Updates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update available.
        /// </summary>
        internal static string Updates_0 {
            get {
                return ResourceManager.GetString("Updates.0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dell Peripheral Manager will close and reopen once updates are completed. Once updates have started, they cannot be cancelled..
        /// </summary>
        internal static string Updates_1 {
            get {
                return ResourceManager.GetString("Updates.1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for updates.
        /// </summary>
        internal static string Updates_2 {
            get {
                return ResourceManager.GetString("Updates.2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no available updates at this time..
        /// </summary>
        internal static string Updates_3 {
            get {
                return ResourceManager.GetString("Updates.3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network error. Please try again..
        /// </summary>
        internal static string Updates_4 {
            get {
                return ResourceManager.GetString("Updates.4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download and install.
        /// </summary>
        internal static string Updates_5 {
            get {
                return ResourceManager.GetString("Updates.5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparing for updates. Please wait....
        /// </summary>
        internal static string Updates_6 {
            get {
                return ResourceManager.GetString("Updates.6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Others.
        /// </summary>
        internal static string VbarText_DisplayOthers {
            get {
                return ResourceManager.GetString("VbarText_DisplayOthers", resourceCulture);
            }
        }
    }
}
