//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDPM.UI.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ThirdPartyLicense_NKVM {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public ThirdPartyLicense_NKVM() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DDPM.UI.Resources.ThirdPartyLicense_NKVM", typeof(ThirdPartyLicense_NKVM).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the “Software”), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
        ///The above copyright notice and this permission notice shall be included in all [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Content1 {
            get {
                return ResourceManager.GetString("Content1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission is hereby granted, free of charge, to any person obtaining a copy
        ///of this software and associated documentation files (the &quot;Software&quot;), to deal
        ///in the Software without restriction, including without limitation the rights
        ///to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
        ///copies of the Software, and to permit persons to whom the Software is
        ///furnished to do so, subject to the following conditions:
        ///
        ///The above copyright notice and this permission notice shall be included [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Content10 {
            get {
                return ResourceManager.GetString("Content10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission is hereby granted, free of charge, to any person obtaining a copy
        ///of this software and associated documentation files (the &quot;Software&quot;), to deal
        ///in the Software without restriction, including without limitation the rights
        ///to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
        ///copies of the Software, and to permit persons to whom the Software is
        ///furnished to do so, subject to the following conditions:
        ///
        ///The above copyright notice and this permission notice shall be included [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Content11 {
            get {
                return ResourceManager.GetString("Content11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ___________________________________________________
        ///These license terms are an agreement between Microsoft Corporation (or based on where you live, one of its affiliates) and you. Please read them. They apply to the software named above, which includes the media on which you received it, if any. The terms also apply to any Microsoft
        ///• updates,
        ///• supplements,
        ///• Internet-based services, and 
        ///• support services
        ///for this software, unless other terms accompany those items. If so, those terms apply.
        ///______ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Content12 {
            get {
                return ResourceManager.GetString("Content12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission is hereby granted, free of charge, to any person obtaining a copy
        ///of this software and associated documentation files (the &quot;Software&quot;), to deal
        ///in the Software without restriction, including without limitation the rights
        ///to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
        ///copies of the Software, and to permit persons to whom the Software is
        ///furnished to do so, subject to the following conditions:
        ///
        ///The above copyright notice and this permission notice shall be included [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Content13 {
            get {
                return ResourceManager.GetString("Content13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission is hereby granted, free of charge, to any person obtaining a copy
        ///of this software and associated documentation files (the &quot;Software&quot;), to deal
        ///in the Software without restriction, including without limitation the rights
        ///to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
        ///copies of the Software, and to permit persons to whom the Software is
        ///furnished to do so, subject to the following conditions:
        ///
        ///The above copyright notice and this permission notice shall be included [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Content14 {
            get {
                return ResourceManager.GetString("Content14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission is hereby granted, free of charge, to any person obtaining a copy
        ///of this software and associated documentation files (the &quot;Software&quot;), to deal
        ///in the Software without restriction, including without limitation the rights
        ///to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
        ///copies of the Software, and to permit persons to whom the Software is
        ///furnished to do so, subject to the following conditions:
        ///
        ///The above copyright notice and this permission notice shall be included [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Content15 {
            get {
                return ResourceManager.GetString("Content15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the &quot;Software&quot;), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
        ///
        ///  The above copyright notice and this permission notice shall be included in [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Content16 {
            get {
                return ResourceManager.GetString("Content16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission is hereby granted, free of charge, to any person obtaining a copy
        ///      of this software and associated documentation files (the &quot;Software&quot;), to deal
        ///      in the Software without restriction, including without limitation the rights
        ///      to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
        ///      copies of the Software, and to permit persons to whom the Software is
        ///      furnished to do so, subject to the following conditions:
        ///
        ///      The above copyright notice and this [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Content17 {
            get {
                return ResourceManager.GetString("Content17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redistribution and use in source and binary forms, with or without
        ///  modification, are permitted provided that the following conditions are
        ///  met:
        ///
        ///      * Redistributions of source code must retain the above copyright
        ///  notice, this list of conditions and the following disclaimer.
        ///      * Redistributions in binary form must reproduce the above
        ///  copyright notice, this list of conditions and the following disclaimer
        ///          in the documentation and/or other materials provided with the
        ///  distribut [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Content18 {
            get {
                return ResourceManager.GetString("Content18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission is hereby granted, free of charge, to any person obtaining a copy
        ///  of this software and associated documentation files (the &quot;Software&quot;), to deal
        ///  in the Software without restriction, including without limitation the rights
        ///          to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
        ///  copies of the Software, and to permit persons to whom the Software is
        ///  furnished to do so, subject to the following conditions:
        ///
        ///  The above copyright notice and this permission noti [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Content19 {
            get {
                return ResourceManager.GetString("Content19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission is hereby granted, free of charge, to any person obtaining a copy
        ///of this software and associated documentation files (the &quot;Software&quot;), to deal
        ///in the Software without restriction, including without limitation the rights
        ///to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
        ///copies of the Software, and to permit persons to whom the Software is
        ///furnished to do so, subject to the following conditions:
        ///
        ///The above copyright notice and this permission notice shall be included [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Content2 {
            get {
                return ResourceManager.GetString("Content2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applicable licenses
        ///          All NSIS source code, plug-ins, documentation, examples, header files and graphics, with the exception of the compression modules and where otherwise noted, are licensed under the zlib/libpng license.
        ///          The zlib compression module for NSIS is licensed under the zlib/libpng license.
        ///  The bzip2 compression module for NSIS is licensed under the bzip2 license.
        ///  The lzma compression module for NSIS is licensed under the Common Public License version 1.0.
        ///
        ///          z [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Content20 {
            get {
                return ResourceManager.GetString("Content20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TERMS AND CONDITIONS FOR USE, REPRODUCTION, AND DISTRIBUTION
        ///
        ///  1. Definitions.
        ///
        ///  &quot;License&quot; shall mean the terms and conditions for use, reproduction, and
        ///  distribution as defined by Sections 1 through 9 of this document.
        ///
        ///  &quot;Licensor&quot; shall mean the copyright owner or entity authorized by the copyright
        ///  owner that is granting the License.
        ///
        ///  &quot;Legal Entity&quot; shall mean the union of the acting entity and all other entities
        ///  that control, are controlled by, or are under common control with that  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Content21 {
            get {
                return ResourceManager.GetString("Content21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TERMS AND CONDITIONS FOR USE, REPRODUCTION, AND DISTRIBUTION
        ///
        ///  1. Definitions.
        ///
        ///  &quot;License&quot; shall mean the terms and conditions for use, reproduction, and
        ///  distribution as defined by Sections 1 through 9 of this document.
        ///
        ///  &quot;Licensor&quot; shall mean the copyright owner or entity authorized by the copyright
        ///  owner that is granting the License.
        ///
        ///  &quot;Legal Entity&quot; shall mean the union of the acting entity and all other entities
        ///  that control, are controlled by, or are under common control with that  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Content22 {
            get {
                return ResourceManager.GetString("Content22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TERMS AND CONDITIONS FOR USE, REPRODUCTION, AND DISTRIBUTION
        ///
        ///  1. Definitions.
        ///
        ///  &quot;License&quot; shall mean the terms and conditions for use, reproduction, and
        ///  distribution as defined by Sections 1 through 9 of this document.
        ///
        ///  &quot;Licensor&quot; shall mean the copyright owner or entity authorized by the copyright
        ///  owner that is granting the License.
        ///
        ///  &quot;Legal Entity&quot; shall mean the union of the acting entity and all other entities
        ///  that control, are controlled by, or are under common control with that  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Content23 {
            get {
                return ResourceManager.GetString("Content23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission is hereby granted, free of charge, to any person obtaining a copy
        ///  of this software and associated documentation files (the &quot;Software&quot;), to deal
        ///  in the Software without restriction, including without limitation the rights
        ///          to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
        ///  copies of the Software, and to permit persons to whom the Software is
        ///  furnished to do so, subject to the following conditions:
        ///
        ///  The above copyright notice and this permission noti [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Content24 {
            get {
                return ResourceManager.GetString("Content24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License text
        ///   MIT License _____
        ///
        ///          Permission is hereby granted, free of charge, to any person obtaining a copy of _____ (the &quot;Software&quot;), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
        ///
        ///  The above copyright notice and this permission notice (including the  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Content25 {
            get {
                return ResourceManager.GetString("Content25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These license terms are an agreement between Microsoft Corporation (or based on where you live, one of its affiliates) and you. Please read them. They apply to the software named above, which includes the media on which you received it, if any. The terms also apply to any Microsoft
        ///  • updates,
        ///  • supplements,
        ///  • Internet-based services, and 
        ///  • support services
        ///  for this software, unless other terms accompany those items. If so, those terms apply.
        ///  _______________________________________________ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Content26 {
            get {
                return ResourceManager.GetString("Content26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These license terms are an agreement between Microsoft Corporation (or based on where you live, one of its affiliates) and you. Please read them. They apply to the software named above, which includes the media on which you received it, if any. The terms also apply to any Microsoft
        ///  • updates,
        ///  • supplements,
        ///  • Internet-based services, and 
        ///  • support services
        ///  for this software, unless other terms accompany those items. If so, those terms apply.
        ///  _______________________________________________ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Content27 {
            get {
                return ResourceManager.GetString("Content27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission is hereby granted, free of charge, to any person obtaining a copy
        ///of this software and associated documentation files (the &quot;Software&quot;), to deal
        ///in the Software without restriction, including without limitation the rights
        ///to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
        ///copies of the Software, and to permit persons to whom the Software is
        ///furnished to do so, subject to the following conditions:
        ///
        ///The above copyright notice and this permission notice shall be included [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Content3 {
            get {
                return ResourceManager.GetString("Content3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission is hereby granted, free of charge, to any person obtaining a copy
        ///of this software and associated documentation files (the &quot;Software&quot;), to deal
        ///in the Software without restriction, including without limitation the rights
        ///to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
        ///copies of the Software, and to permit persons to whom the Software is
        ///furnished to do so, subject to the following conditions:
        ///
        ///The above copyright notice and this permission notice shall be included [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Content4 {
            get {
                return ResourceManager.GetString("Content4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission is hereby granted, free of charge, to any person obtaining a copy
        ///of this software and associated documentation files (the &quot;Software&quot;), to deal
        ///in the Software without restriction, including without limitation the rights
        ///to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
        ///copies of the Software, and to permit persons to whom the Software is
        ///furnished to do so, subject to the following conditions:
        ///
        ///The above copyright notice and this permission notice shall be included [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Content5 {
            get {
                return ResourceManager.GetString("Content5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the “Software”), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
        ///The above copyright notice and this permission notice shall be included in all [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Content6 {
            get {
                return ResourceManager.GetString("Content6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ___________________________________________________
        ///These license terms are an agreement between Microsoft Corporation (or based on where you live, one of its affiliates) and you. Please read them. They apply to the software named above, which includes the media on which you received it, if any. The terms also apply to any Microsoft
        ///• updates,
        ///• supplements,
        ///• Internet-based services, and 
        ///• support services
        ///for this software, unless other terms accompany those items. If so, those terms apply.
        ///______ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Content7 {
            get {
                return ResourceManager.GetString("Content7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the &quot;Software&quot;), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
        ///The above copyright notice and this permission notice shall be included in all [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Content8 {
            get {
                return ResourceManager.GetString("Content8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission is hereby granted, free of charge, to any person obtaining a copy
        ///of this software and associated documentation files (the &quot;Software&quot;), to deal
        ///in the Software without restriction, including without limitation the rights
        ///to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
        ///copies of the Software, and to permit persons to whom the Software is
        ///furnished to do so, subject to the following conditions:
        ///
        ///The above copyright notice and this permission notice shall be included [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Content9 {
            get {
                return ResourceManager.GetString("Content9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CommunityToolkit.Mvvm 8.1.0
        ///
        ///Copyright © .NET Foundation and Contributors
        ///All rights reserved.
        ///MIT License (MIT)
        ///.
        /// </summary>
        public static string Title1 {
            get {
                return ResourceManager.GetString("Title1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.Management 8.0.0
        ///The MIT License (MIT)
        ///
        ///Copyright (c) .NET Foundation and Contributors
        ///
        ///All rights reserved.
        ///.
        /// </summary>
        public static string Title10 {
            get {
                return ResourceManager.GetString("Title10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.Text.Json 8.0.4
        ///The MIT License (MIT)
        ///
        ///Copyright (c) .NET Foundation and Contributors
        ///
        ///All rights reserved.
        ///.
        /// </summary>
        public static string Title11 {
            get {
                return ResourceManager.GetString("Title11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WinCopies.WindowsAPICodePack.Shell 2.12.0.2
        ///License: Custom License
        ///All the code of the WinCopies Windows API Code Pack, unless otherwise noted, is licensed under the following terms and conditions:
        ///MICROSOFT SOFTWARE LICENSE TERMS
        ///MICROSOFT WINDOWS API CODE PACK FOR MICROSOFT .NET FRAMEWORK/.NET CORE
        ///.
        /// </summary>
        public static string Title12 {
            get {
                return ResourceManager.GetString("Title12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft.Xaml.Behaviors.Wpf 1.1.77
        ///The MIT License (MIT)
        ///
        ///Copyright (c) 2015 Microsoft
        ///.
        /// </summary>
        public static string Title13 {
            get {
                return ResourceManager.GetString("Title13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.Collections 4.3.0
        ///The MIT License (MIT)
        ///
        ///Copyright (c) .NET Foundation and Contributors
        ///
        ///All rights reserved.
        ///.
        /// </summary>
        public static string Title14 {
            get {
                return ResourceManager.GetString("Title14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.Resources.Extensions 8.0.0
        ///The MIT License (MIT)
        ///
        ///Copyright (c) .NET Foundation and Contributors
        ///
        ///All rights reserved.
        ///.
        /// </summary>
        public static string Title15 {
            get {
                return ResourceManager.GetString("Title15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Core.System.Configuration.Install v1.1.0
        ///
        ///MIT License (MIT)
        ///Copyright (c) 2018 Alexander Chermyanin
        ///
        ///.
        /// </summary>
        public static string Title16 {
            get {
                return ResourceManager.GetString("Title16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dev-tunnels-ssh v3.11.38
        ///
        ///    MIT License
        ///    Copyright (c) Microsoft Corporation.
        ///
        ///.
        /// </summary>
        public static string Title17 {
            get {
                return ResourceManager.GetString("Title17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google.Protobuf v3.20.0
        ///
        ///Copyright 2008 Google Inc.  All rights reserved.
        ///
        ///.
        /// </summary>
        public static string Title18 {
            get {
                return ResourceManager.GetString("Title18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModernWpfUI v0.9.6
        ///
        ///MIT License
        ///
        ///Copyright (c) 2019 Yimeng Wu
        ///
        ///.
        /// </summary>
        public static string Title19 {
            get {
                return ResourceManager.GetString("Title19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H.Formatters.Inferno 2.0.59
        ///The MIT License (MIT)
        ///
        ///Copyright (c) havendv and Andrew C. Dvorak &lt;andy@andydvorak.net&gt;
        ///.
        /// </summary>
        public static string Title2 {
            get {
                return ResourceManager.GetString("Title2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NSIS v3.10_Custom
        ///
        ///Copyright
        ///Copyright (C) 1999-2023 Contributors
        ///
        ///More detailed copyright information can be found in the individual source code files.
        ///
        ///.
        /// </summary>
        public static string Title20 {
            get {
                return ResourceManager.GetString("Title20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serilog.Sinks.Async v1.5.0
        ///
        ///Apache License
        ///Version 2.0, January 2004
        ///http://www.apache.org/licenses/
        ///
        ///.
        /// </summary>
        public static string Title21 {
            get {
                return ResourceManager.GetString("Title21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serilog.Sinks.File v5.0.0
        ///
        ///Apache License
        ///Version 2.0, January 2004
        ///http://www.apache.org/licenses/
        ///
        ///.
        /// </summary>
        public static string Title22 {
            get {
                return ResourceManager.GetString("Title22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serilog v3.1.1
        ///
        ///Apache License
        ///Version 2.0, January 2004
        ///http://www.apache.org/licenses/
        ///
        ///.
        /// </summary>
        public static string Title23 {
            get {
                return ResourceManager.GetString("Title23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SSH.NET 2024.1.0
        ///
        ///The MIT License (MIT)
        ///
        ///Copyright (c) Renci, Oleg Kapeljushnik, Gert Driesen and contributors
        ///
        ///.
        /// </summary>
        public static string Title24 {
            get {
                return ResourceManager.GetString("Title24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.Management v8.0.0
        ///
        ///SPDX identifier
        ///MIT
        ///
        ///.
        /// </summary>
        public static string Title25 {
            get {
                return ResourceManager.GetString("Title25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WinCopies.WindowsAPICodePack.Win32Native 2.12.0.0_Custom
        ///
        ///License: Custom License
        ///All the code of the WinCopies Windows API Code Pack, unless otherwise noted, is licensed under the following terms and conditions:
        ///MICROSOFT SOFTWARE LICENSE TERMS
        ///MICROSOFT WINDOWS API CODE PACK FOR MICROSOFT .NET FRAMEWORK/.NET CORE
        ///
        ///.
        /// </summary>
        public static string Title26 {
            get {
                return ResourceManager.GetString("Title26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WinCopies.WindowsAPICodePack 2.12.0.0_Custom
        ///
        ///License: Custom License
        ///All the code of the WinCopies Windows API Code Pack, unless otherwise noted, is licensed under the following terms and conditions:
        ///MICROSOFT SOFTWARE LICENSE TERMS
        ///MICROSOFT WINDOWS API CODE PACK FOR MICROSOFT .NET FRAMEWORK/.NET CORE
        ///
        ///.
        /// </summary>
        public static string Title27 {
            get {
                return ResourceManager.GetString("Title27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H.Formatters.Newtonsoft.Json 13.0.59
        ///
        ///The MIT License (MIT)
        ///
        ///Copyright (c) havendv and Andrew C. Dvorak &lt;andy@andydvorak.net&gt;
        ///.
        /// </summary>
        public static string Title3 {
            get {
                return ResourceManager.GetString("Title3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H.Pipes 2.0.59
        ///The MIT License (MIT)
        ///
        ///Copyright (c) havendv and Andrew C. Dvorak &lt;andy@andydvorak.net&gt;
        ///.
        /// </summary>
        public static string Title4 {
            get {
                return ResourceManager.GetString("Title4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H.Pipes.AccessControl 2.0.59
        ///
        ///Copyright (c) havendv and Andrew C. Dvorak &lt;andy@andydvorak.net&gt;
        ///.
        /// </summary>
        public static string Title5 {
            get {
                return ResourceManager.GetString("Title5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft.Toolkit.Uwp.Notifications 7.1.3
        ///Copyright © .NET Foundation and Contributors
        ///All rights reserved.
        ///MIT License (MIT)
        ///.
        /// </summary>
        public static string Title6 {
            get {
                return ResourceManager.GetString("Title6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft-WindowsAPICodePack-Shell 1.1.5
        ///License: Custom License
        ///MICROSOFT SOFTWARE LICENSE TERMS
        ///MICROSOFT WINDOWS API CODE PACK FOR MICROSOFT .NET FRAMEWORK
        ///.
        /// </summary>
        public static string Title7 {
            get {
                return ResourceManager.GetString("Title7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Newtonsoft.Json 13.0.3
        ///The MIT License (MIT) 
        ///Copyright (c) 2007 James Newton-King
        ///.
        /// </summary>
        public static string Title8 {
            get {
                return ResourceManager.GetString("Title8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.Drawing.Common 8.0.7
        ///The MIT License (MIT)
        ///
        ///Copyright (c) .NET Foundation and Contributors
        ///
        ///All rights reserved.
        ///.
        /// </summary>
        public static string Title9 {
            get {
                return ResourceManager.GetString("Title9", resourceCulture);
            }
        }
    }
}
