//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DDPM.UI.Resources {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ThirdPartyLicense_NKVM {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ThirdPartyLicense_NKVM() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DDPM.UI.Resources.ThirdPartyLicense_NKVM", typeof(ThirdPartyLicense_NKVM).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the “Software”), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
        ///The above copyright notice and this permission notice shall be included in all [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string Content1 {
            get {
                return ResourceManager.GetString("Content1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Permission is hereby granted, free of charge, to any person obtaining a copy
        ///of this software and associated documentation files (the &quot;Software&quot;), to deal
        ///in the Software without restriction, including without limitation the rights
        ///to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
        ///copies of the Software, and to permit persons to whom the Software is
        ///furnished to do so, subject to the following conditions:
        ///
        ///The above copyright notice and this permission notice shall be included [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string Content10 {
            get {
                return ResourceManager.GetString("Content10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Permission is hereby granted, free of charge, to any person obtaining a copy
        ///of this software and associated documentation files (the &quot;Software&quot;), to deal
        ///in the Software without restriction, including without limitation the rights
        ///to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
        ///copies of the Software, and to permit persons to whom the Software is
        ///furnished to do so, subject to the following conditions:
        ///
        ///The above copyright notice and this permission notice shall be included [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string Content11 {
            get {
                return ResourceManager.GetString("Content11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ___________________________________________________
        ///These license terms are an agreement between Microsoft Corporation (or based on where you live, one of its affiliates) and you. Please read them. They apply to the software named above, which includes the media on which you received it, if any. The terms also apply to any Microsoft
        ///• updates,
        ///• supplements,
        ///• Internet-based services, and 
        ///• support services
        ///for this software, unless other terms accompany those items. If so, those terms apply.
        ///______ [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string Content12 {
            get {
                return ResourceManager.GetString("Content12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Permission is hereby granted, free of charge, to any person obtaining a copy
        ///of this software and associated documentation files (the &quot;Software&quot;), to deal
        ///in the Software without restriction, including without limitation the rights
        ///to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
        ///copies of the Software, and to permit persons to whom the Software is
        ///furnished to do so, subject to the following conditions:
        ///
        ///The above copyright notice and this permission notice shall be included [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string Content13 {
            get {
                return ResourceManager.GetString("Content13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Permission is hereby granted, free of charge, to any person obtaining a copy
        ///of this software and associated documentation files (the &quot;Software&quot;), to deal
        ///in the Software without restriction, including without limitation the rights
        ///to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
        ///copies of the Software, and to permit persons to whom the Software is
        ///furnished to do so, subject to the following conditions:
        ///
        ///The above copyright notice and this permission notice shall be included [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string Content14 {
            get {
                return ResourceManager.GetString("Content14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Permission is hereby granted, free of charge, to any person obtaining a copy
        ///of this software and associated documentation files (the &quot;Software&quot;), to deal
        ///in the Software without restriction, including without limitation the rights
        ///to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
        ///copies of the Software, and to permit persons to whom the Software is
        ///furnished to do so, subject to the following conditions:
        ///
        ///The above copyright notice and this permission notice shall be included [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string Content15 {
            get {
                return ResourceManager.GetString("Content15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the &quot;Software&quot;), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
        ///
        ///  The above copyright notice and this permission notice shall be included in [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string Content16 {
            get {
                return ResourceManager.GetString("Content16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Permission is hereby granted, free of charge, to any person obtaining a copy
        ///      of this software and associated documentation files (the &quot;Software&quot;), to deal
        ///      in the Software without restriction, including without limitation the rights
        ///      to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
        ///      copies of the Software, and to permit persons to whom the Software is
        ///      furnished to do so, subject to the following conditions:
        ///
        ///      The above copyright notice and this [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string Content17 {
            get {
                return ResourceManager.GetString("Content17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Redistribution and use in source and binary forms, with or without
        ///  modification, are permitted provided that the following conditions are
        ///  met:
        ///
        ///      * Redistributions of source code must retain the above copyright
        ///  notice, this list of conditions and the following disclaimer.
        ///      * Redistributions in binary form must reproduce the above
        ///  copyright notice, this list of conditions and the following disclaimer
        ///          in the documentation and/or other materials provided with the
        ///  distribut [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string Content18 {
            get {
                return ResourceManager.GetString("Content18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Permission is hereby granted, free of charge, to any person obtaining a copy
        ///  of this software and associated documentation files (the &quot;Software&quot;), to deal
        ///  in the Software without restriction, including without limitation the rights
        ///          to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
        ///  copies of the Software, and to permit persons to whom the Software is
        ///  furnished to do so, subject to the following conditions:
        ///
        ///  The above copyright notice and this permission noti [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string Content19 {
            get {
                return ResourceManager.GetString("Content19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Permission is hereby granted, free of charge, to any person obtaining a copy
        ///of this software and associated documentation files (the &quot;Software&quot;), to deal
        ///in the Software without restriction, including without limitation the rights
        ///to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
        ///copies of the Software, and to permit persons to whom the Software is
        ///furnished to do so, subject to the following conditions:
        ///
        ///The above copyright notice and this permission notice shall be included [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string Content2 {
            get {
                return ResourceManager.GetString("Content2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Applicable licenses
        ///          All NSIS source code, plug-ins, documentation, examples, header files and graphics, with the exception of the compression modules and where otherwise noted, are licensed under the zlib/libpng license.
        ///          The zlib compression module for NSIS is licensed under the zlib/libpng license.
        ///  The bzip2 compression module for NSIS is licensed under the bzip2 license.
        ///  The lzma compression module for NSIS is licensed under the Common Public License version 1.0.
        ///
        ///          z [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string Content20 {
            get {
                return ResourceManager.GetString("Content20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 TERMS AND CONDITIONS FOR USE, REPRODUCTION, AND DISTRIBUTION
        ///
        ///  1. Definitions.
        ///
        ///  &quot;License&quot; shall mean the terms and conditions for use, reproduction, and
        ///  distribution as defined by Sections 1 through 9 of this document.
        ///
        ///  &quot;Licensor&quot; shall mean the copyright owner or entity authorized by the copyright
        ///  owner that is granting the License.
        ///
        ///  &quot;Legal Entity&quot; shall mean the union of the acting entity and all other entities
        ///  that control, are controlled by, or are under common control with that  [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string Content21 {
            get {
                return ResourceManager.GetString("Content21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 TERMS AND CONDITIONS FOR USE, REPRODUCTION, AND DISTRIBUTION
        ///
        ///  1. Definitions.
        ///
        ///  &quot;License&quot; shall mean the terms and conditions for use, reproduction, and
        ///  distribution as defined by Sections 1 through 9 of this document.
        ///
        ///  &quot;Licensor&quot; shall mean the copyright owner or entity authorized by the copyright
        ///  owner that is granting the License.
        ///
        ///  &quot;Legal Entity&quot; shall mean the union of the acting entity and all other entities
        ///  that control, are controlled by, or are under common control with that  [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string Content22 {
            get {
                return ResourceManager.GetString("Content22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 TERMS AND CONDITIONS FOR USE, REPRODUCTION, AND DISTRIBUTION
        ///
        ///  1. Definitions.
        ///
        ///  &quot;License&quot; shall mean the terms and conditions for use, reproduction, and
        ///  distribution as defined by Sections 1 through 9 of this document.
        ///
        ///  &quot;Licensor&quot; shall mean the copyright owner or entity authorized by the copyright
        ///  owner that is granting the License.
        ///
        ///  &quot;Legal Entity&quot; shall mean the union of the acting entity and all other entities
        ///  that control, are controlled by, or are under common control with that  [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string Content23 {
            get {
                return ResourceManager.GetString("Content23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Permission is hereby granted, free of charge, to any person obtaining a copy
        ///  of this software and associated documentation files (the &quot;Software&quot;), to deal
        ///  in the Software without restriction, including without limitation the rights
        ///          to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
        ///  copies of the Software, and to permit persons to whom the Software is
        ///  furnished to do so, subject to the following conditions:
        ///
        ///  The above copyright notice and this permission noti [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string Content24 {
            get {
                return ResourceManager.GetString("Content24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 License text
        ///   MIT License _____
        ///
        ///          Permission is hereby granted, free of charge, to any person obtaining a copy of _____ (the &quot;Software&quot;), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
        ///
        ///  The above copyright notice and this permission notice (including the  [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string Content25 {
            get {
                return ResourceManager.GetString("Content25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 These license terms are an agreement between Microsoft Corporation (or based on where you live, one of its affiliates) and you. Please read them. They apply to the software named above, which includes the media on which you received it, if any. The terms also apply to any Microsoft
        ///  • updates,
        ///  • supplements,
        ///  • Internet-based services, and 
        ///  • support services
        ///  for this software, unless other terms accompany those items. If so, those terms apply.
        ///  _______________________________________________ [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string Content26 {
            get {
                return ResourceManager.GetString("Content26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 These license terms are an agreement between Microsoft Corporation (or based on where you live, one of its affiliates) and you. Please read them. They apply to the software named above, which includes the media on which you received it, if any. The terms also apply to any Microsoft
        ///  • updates,
        ///  • supplements,
        ///  • Internet-based services, and 
        ///  • support services
        ///  for this software, unless other terms accompany those items. If so, those terms apply.
        ///  _______________________________________________ [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string Content27 {
            get {
                return ResourceManager.GetString("Content27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Permission is hereby granted, free of charge, to any person obtaining a copy
        ///of this software and associated documentation files (the &quot;Software&quot;), to deal
        ///in the Software without restriction, including without limitation the rights
        ///to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
        ///copies of the Software, and to permit persons to whom the Software is
        ///furnished to do so, subject to the following conditions:
        ///
        ///The above copyright notice and this permission notice shall be included [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string Content3 {
            get {
                return ResourceManager.GetString("Content3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Permission is hereby granted, free of charge, to any person obtaining a copy
        ///of this software and associated documentation files (the &quot;Software&quot;), to deal
        ///in the Software without restriction, including without limitation the rights
        ///to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
        ///copies of the Software, and to permit persons to whom the Software is
        ///furnished to do so, subject to the following conditions:
        ///
        ///The above copyright notice and this permission notice shall be included [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string Content4 {
            get {
                return ResourceManager.GetString("Content4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Permission is hereby granted, free of charge, to any person obtaining a copy
        ///of this software and associated documentation files (the &quot;Software&quot;), to deal
        ///in the Software without restriction, including without limitation the rights
        ///to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
        ///copies of the Software, and to permit persons to whom the Software is
        ///furnished to do so, subject to the following conditions:
        ///
        ///The above copyright notice and this permission notice shall be included [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string Content5 {
            get {
                return ResourceManager.GetString("Content5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the “Software”), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
        ///The above copyright notice and this permission notice shall be included in all [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string Content6 {
            get {
                return ResourceManager.GetString("Content6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ___________________________________________________
        ///These license terms are an agreement between Microsoft Corporation (or based on where you live, one of its affiliates) and you. Please read them. They apply to the software named above, which includes the media on which you received it, if any. The terms also apply to any Microsoft
        ///• updates,
        ///• supplements,
        ///• Internet-based services, and 
        ///• support services
        ///for this software, unless other terms accompany those items. If so, those terms apply.
        ///______ [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string Content7 {
            get {
                return ResourceManager.GetString("Content7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the &quot;Software&quot;), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
        ///The above copyright notice and this permission notice shall be included in all [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string Content8 {
            get {
                return ResourceManager.GetString("Content8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Permission is hereby granted, free of charge, to any person obtaining a copy
        ///of this software and associated documentation files (the &quot;Software&quot;), to deal
        ///in the Software without restriction, including without limitation the rights
        ///to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
        ///copies of the Software, and to permit persons to whom the Software is
        ///furnished to do so, subject to the following conditions:
        ///
        ///The above copyright notice and this permission notice shall be included [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string Content9 {
            get {
                return ResourceManager.GetString("Content9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 CommunityToolkit.Mvvm 8.1.0
        ///
        ///Copyright © .NET Foundation and Contributors
        ///All rights reserved.
        ///MIT License (MIT)
        /// 的當地語系化字串。
        /// </summary>
        internal static string Title1 {
            get {
                return ResourceManager.GetString("Title1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 System.Management 8.0.0
        ///The MIT License (MIT)
        ///
        ///Copyright (c) .NET Foundation and Contributors
        ///
        ///All rights reserved.
        /// 的當地語系化字串。
        /// </summary>
        internal static string Title10 {
            get {
                return ResourceManager.GetString("Title10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 System.Text.Json 8.0.4
        ///The MIT License (MIT)
        ///
        ///Copyright (c) .NET Foundation and Contributors
        ///
        ///All rights reserved.
        /// 的當地語系化字串。
        /// </summary>
        internal static string Title11 {
            get {
                return ResourceManager.GetString("Title11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 WinCopies.WindowsAPICodePack.Shell 2.12.0.2
        ///License: Custom License
        ///All the code of the WinCopies Windows API Code Pack, unless otherwise noted, is licensed under the following terms and conditions:
        ///MICROSOFT SOFTWARE LICENSE TERMS
        ///MICROSOFT WINDOWS API CODE PACK FOR MICROSOFT .NET FRAMEWORK/.NET CORE
        /// 的當地語系化字串。
        /// </summary>
        internal static string Title12 {
            get {
                return ResourceManager.GetString("Title12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Microsoft.Xaml.Behaviors.Wpf 1.1.77
        ///The MIT License (MIT)
        ///
        ///Copyright (c) 2015 Microsoft
        /// 的當地語系化字串。
        /// </summary>
        internal static string Title13 {
            get {
                return ResourceManager.GetString("Title13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 System.Collections 4.3.0
        ///The MIT License (MIT)
        ///
        ///Copyright (c) .NET Foundation and Contributors
        ///
        ///All rights reserved.
        /// 的當地語系化字串。
        /// </summary>
        internal static string Title14 {
            get {
                return ResourceManager.GetString("Title14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 System.Resources.Extensions 8.0.0
        ///The MIT License (MIT)
        ///
        ///Copyright (c) .NET Foundation and Contributors
        ///
        ///All rights reserved.
        /// 的當地語系化字串。
        /// </summary>
        internal static string Title15 {
            get {
                return ResourceManager.GetString("Title15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Core.System.Configuration.Install v1.1.0
        ///
        ///MIT License (MIT)
        ///Copyright (c) 2018 Alexander Chermyanin
        ///
        /// 的當地語系化字串。
        /// </summary>
        internal static string Title16 {
            get {
                return ResourceManager.GetString("Title16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 dev-tunnels-ssh v3.11.38
        ///
        ///    MIT License
        ///    Copyright (c) Microsoft Corporation.
        ///
        /// 的當地語系化字串。
        /// </summary>
        internal static string Title17 {
            get {
                return ResourceManager.GetString("Title17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Google.Protobuf v3.20.0
        ///
        ///Copyright 2008 Google Inc.  All rights reserved.
        ///
        /// 的當地語系化字串。
        /// </summary>
        internal static string Title18 {
            get {
                return ResourceManager.GetString("Title18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ModernWpfUI v0.9.6
        ///
        ///MIT License
        ///
        ///Copyright (c) 2019 Yimeng Wu
        ///
        /// 的當地語系化字串。
        /// </summary>
        internal static string Title19 {
            get {
                return ResourceManager.GetString("Title19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 H.Formatters.Inferno 2.0.59
        ///The MIT License (MIT)
        ///
        ///Copyright (c) havendv and Andrew C. Dvorak &lt;andy@andydvorak.net&gt;
        /// 的當地語系化字串。
        /// </summary>
        internal static string Title2 {
            get {
                return ResourceManager.GetString("Title2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 NSIS v3.10_Custom
        ///
        ///Copyright
        ///Copyright (C) 1999-2023 Contributors
        ///
        ///More detailed copyright information can be found in the individual source code files.
        ///
        /// 的當地語系化字串。
        /// </summary>
        internal static string Title20 {
            get {
                return ResourceManager.GetString("Title20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Serilog.Sinks.Async v1.5.0
        ///
        ///Apache License
        ///Version 2.0, January 2004
        ///http://www.apache.org/licenses/
        ///
        /// 的當地語系化字串。
        /// </summary>
        internal static string Title21 {
            get {
                return ResourceManager.GetString("Title21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Serilog.Sinks.File v5.0.0
        ///
        ///Apache License
        ///Version 2.0, January 2004
        ///http://www.apache.org/licenses/
        ///
        /// 的當地語系化字串。
        /// </summary>
        internal static string Title22 {
            get {
                return ResourceManager.GetString("Title22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Serilog v3.1.1
        ///
        ///Apache License
        ///Version 2.0, January 2004
        ///http://www.apache.org/licenses/
        ///
        /// 的當地語系化字串。
        /// </summary>
        internal static string Title23 {
            get {
                return ResourceManager.GetString("Title23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 SSH.NET 2024.1.0
        ///
        ///The MIT License (MIT)
        ///
        ///Copyright (c) Renci, Oleg Kapeljushnik, Gert Driesen and contributors
        ///
        /// 的當地語系化字串。
        /// </summary>
        internal static string Title24 {
            get {
                return ResourceManager.GetString("Title24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 System.Management v8.0.0
        ///
        ///SPDX identifier
        ///MIT
        ///
        /// 的當地語系化字串。
        /// </summary>
        internal static string Title25 {
            get {
                return ResourceManager.GetString("Title25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 WinCopies.WindowsAPICodePack.Win32Native 2.12.0.0_Custom
        ///
        ///License: Custom License
        ///All the code of the WinCopies Windows API Code Pack, unless otherwise noted, is licensed under the following terms and conditions:
        ///MICROSOFT SOFTWARE LICENSE TERMS
        ///MICROSOFT WINDOWS API CODE PACK FOR MICROSOFT .NET FRAMEWORK/.NET CORE
        ///
        /// 的當地語系化字串。
        /// </summary>
        internal static string Title26 {
            get {
                return ResourceManager.GetString("Title26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 WinCopies.WindowsAPICodePack 2.12.0.0_Custom
        ///
        ///License: Custom License
        ///All the code of the WinCopies Windows API Code Pack, unless otherwise noted, is licensed under the following terms and conditions:
        ///MICROSOFT SOFTWARE LICENSE TERMS
        ///MICROSOFT WINDOWS API CODE PACK FOR MICROSOFT .NET FRAMEWORK/.NET CORE
        ///
        /// 的當地語系化字串。
        /// </summary>
        internal static string Title27 {
            get {
                return ResourceManager.GetString("Title27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 H.Formatters.Newtonsoft.Json 13.0.59
        ///
        ///The MIT License (MIT)
        ///
        ///Copyright (c) havendv and Andrew C. Dvorak &lt;andy@andydvorak.net&gt;
        /// 的當地語系化字串。
        /// </summary>
        internal static string Title3 {
            get {
                return ResourceManager.GetString("Title3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 H.Pipes 2.0.59
        ///The MIT License (MIT)
        ///
        ///Copyright (c) havendv and Andrew C. Dvorak &lt;andy@andydvorak.net&gt;
        /// 的當地語系化字串。
        /// </summary>
        internal static string Title4 {
            get {
                return ResourceManager.GetString("Title4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 H.Pipes.AccessControl 2.0.59
        ///
        ///Copyright (c) havendv and Andrew C. Dvorak &lt;andy@andydvorak.net&gt;
        /// 的當地語系化字串。
        /// </summary>
        internal static string Title5 {
            get {
                return ResourceManager.GetString("Title5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Microsoft.Toolkit.Uwp.Notifications 7.1.3
        ///Copyright © .NET Foundation and Contributors
        ///All rights reserved.
        ///MIT License (MIT)
        /// 的當地語系化字串。
        /// </summary>
        internal static string Title6 {
            get {
                return ResourceManager.GetString("Title6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Microsoft-WindowsAPICodePack-Shell 1.1.5
        ///License: Custom License
        ///MICROSOFT SOFTWARE LICENSE TERMS
        ///MICROSOFT WINDOWS API CODE PACK FOR MICROSOFT .NET FRAMEWORK
        /// 的當地語系化字串。
        /// </summary>
        internal static string Title7 {
            get {
                return ResourceManager.GetString("Title7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Newtonsoft.Json 13.0.3
        ///The MIT License (MIT) 
        ///Copyright (c) 2007 James Newton-King
        /// 的當地語系化字串。
        /// </summary>
        internal static string Title8 {
            get {
                return ResourceManager.GetString("Title8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 System.Drawing.Common 8.0.7
        ///The MIT License (MIT)
        ///
        ///Copyright (c) .NET Foundation and Contributors
        ///
        ///All rights reserved.
        /// 的當地語系化字串。
        /// </summary>
        internal static string Title9 {
            get {
                return ResourceManager.GetString("Title9", resourceCulture);
            }
        }
    }
}
