<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <BaseOutputPath>..\..\bin\CommonDll</BaseOutputPath>
	  <UseWPF>true</UseWPF>
	  <Version>2.0.0.5</Version>
	  <Configurations>Debug;Release;Debug_NKVM</Configurations>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Interfaces\IDPeM.cs" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="UpdateProgressPage\ProgressBackground.png" />
    <None Remove="UpdateProgressPage\ProgressBackground_Light.png" />
  </ItemGroup>

  <ItemGroup>

    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.1.0" />
    <PackageReference Include="DCF.UX.WPF" Version="2.2.4.1" />
    <PackageReference Include="Dell.TechHub.Sdk.Common_NET" Version="3.0.0.606-2e2db9-beta" />
    <PackageReference Include="Dell.RPC.Transport" Version="1.5.2.1" />
    <PackageReference Include="DellClientFramework" Version="6.4.11.2" />
    <PackageReference Include="Microsoft-WindowsAPICodePack-Shell" Version="1.1.5" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\DDPM.RemoteManagement.Common\DDPM.RemoteManagement.Common.csproj" />
    <ProjectReference Include="..\DDPM.SA.Obfuscation\DDPM.SA.Obfuscation.csproj" />
    <ProjectReference Include="..\DDPM.SA.Resources\DDPM.SA.Resources.csproj" />
    <ProjectReference Include="..\VcpCore.Interfaces\VcpCore.Interfaces.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="DdmLibrary">
      <HintPath>..\..\dll\DdmLibrary.dll</HintPath>
    </Reference>
    <Reference Include="DDPM.Peripherals.interface">
      <HintPath>..\..\dll\DDPM.Peripherals.interface.dll</HintPath>
    </Reference>
    <Reference Include="DPeMClientBroker">
      <HintPath>..\..\dll\DPeMClientBroker.dll</HintPath>
    </Reference>
    <Reference Include="DPeMPublic.Common">
      <HintPath>..\..\dll\DPeMPublic.Common.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Resource Include="UpdateProgressPage\ProgressBackground.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
    <Resource Include="UpdateProgressPage\ProgressBackground_Light.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="UI\" />
  </ItemGroup>

  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="xcopy &quot;$(ProjectDir)$(OutDir)DDPM.SA.Common.*&quot; &quot;$(SolutionDir)..\DdpmSwUpdater\CommonDll\&quot; /Y /S /Q" />
  </Target>

</Project>
